'use strict';
(()=>{
 const bridge=window.KaishiGardenBridge,dialog=document.querySelector('#gardenDialog');
 if(!bridge||!dialog)return;
 const positions={
  'smooth-stone':['18%','72%'],'moss-stone':['72%','66%'],bamboo:['83%','22%'],lantern:['25%','24%'],maple:['72%','18%'],'water-basin':['49%','70%']
 };
 const itemMap=()=>new Map(bridge.items().map(item=>[item.id,item]));
 function sceneItems(ids=[]){const items=itemMap();return ids.filter(id=>items.has(id)).map(id=>{const item=items.get(id),position=positions[id]||['50%','50%'];return`<span class="garden-decoration garden-item-${id}" style="--garden-x:${position[0]};--garden-y:${position[1]}" title="${item.name}" aria-label="${item.name}">${item.icon}</span>`}).join('')}
 function gardenScene(state,avatarSrc,shared=false){const leaves=shared?'':Array.from({length:state.behind||0},(_,index)=>`<i class="garden-leaf leaf-${index+1}" aria-hidden="true">🍂</i>`).join('');return`<div class="garden-rake-path" aria-hidden="true"></div><img class="garden-learner" src="${avatarSrc}" alt="${shared?'Friend’s':'Your'} learner avatar tending the garden">${sceneItems(state.placed||state.items)}${leaves}<span class="garden-rake" aria-hidden="true">⌁</span>`}
 function statusMessage(state){if(state.qualified)return'Today’s pattern is complete.';if(state.behind>=2)return'The pattern is fading. Practise today to begin restoring it.';if(state.behind===1)return'A little wind disturbed the sand. Today’s practice will restore it.';return'Your next Japanese practice will extend the pattern.'}
 function render(){const state=bridge.state(),avatar=document.querySelector('#dashboardAvatar')?.src||'media/profiles/guest-learner.webp',miniAvatar=document.querySelector('#gardenMiniAvatar'),streak=document.querySelector('#streak'),miniStatus=document.querySelector('#gardenMiniStatus'),weather=document.querySelector('#gardenMiniWeather'),tokens=document.querySelector('#gardenQuickTokens');if(miniAvatar)miniAvatar.src=avatar;if(streak)streak.textContent=`${state.streak} day${state.streak===1?'':'s'} · Garden streak`;if(miniStatus)miniStatus.textContent=state.qualified?'Garden cared for today':state.behind?`${state.behind} section${state.behind===1?'':'s'} need care`:'Tap to tend your garden';if(weather)weather.textContent='🍂'.repeat(state.behind);if(tokens){tokens.querySelectorAll('i').forEach((token,index)=>token.classList.toggle('used',index<state.quickUsed));tokens.setAttribute('aria-label',`${state.quickRemaining} of 2 Quick Rakes available this week`)}
  const scene=document.querySelector('#gardenScene');if(scene){scene.innerHTML=gardenScene(state,avatar);scene.className=`garden-scene behind-${state.behind}${state.qualified?' cared':''}`}
  const cards=document.querySelector('#gardenStatusCards');if(cards)cards.innerHTML=`<article><strong>${state.streak}</strong><span>day garden journey</span></article><article><strong>${state.behind}/3</strong><span>sections behind</span></article><article><strong>${state.quickRemaining}/2</strong><span>Quick Rakes left</span></article>`;
  const quick=document.querySelector('#gardenQuickRake'),help=document.querySelector('#gardenQuickHelp');if(quick){quick.disabled=state.qualified||!state.quickRemaining;quick.textContent=state.qualified?'✓ Garden cared for today':state.quickRemaining?`Quick Rake · 3 reviews (${state.quickRemaining} left)`:'Quick Rakes used this week'}if(help)help.textContent=statusMessage(state);
  const balance=document.querySelector('#gardenApBalance');if(balance)balance.textContent=`${state.availableAp.toLocaleString()} AP`;
  const store=document.querySelector('#gardenStoreGrid');if(store){store.innerHTML=bridge.items().map(item=>{const owned=state.owned.includes(item.id),placed=state.placed.includes(item.id),affordable=state.availableAp>=item.cost;return`<article class="garden-store-item ${owned?'owned':''}"><span aria-hidden="true">${item.icon}</span><div><strong>${item.name}</strong><small>${item.description}</small></div><button type="button" data-garden-item="${item.id}"${!owned&&!affordable?' disabled':''}>${owned?(placed?'Store':'Place'):(item.cost?`${item.cost} AP`:'Free')}</button></article>`}).join('');store.querySelectorAll('[data-garden-item]').forEach(button=>button.onclick=()=>{const result=bridge.buy(button.dataset.gardenItem);if(help)help.textContent=result.message;render()})}
 }
 function open(){render();if(!dialog.open)dialog.showModal()}
 function preview(state={},avatarSrc='media/profiles/guest-learner.webp'){const safe={items:Array.isArray(state.items)?state.items:[],streak:Number(state.streak||0)};return`<div class="friend-garden-scene">${gardenScene(safe,avatarSrc,true)}</div><div class="friend-garden-caption"><strong>Garden of Practice</strong><span>${safe.streak} day${safe.streak===1?'':'s'} · ${safe.items.length} decoration${safe.items.length===1?'':'s'}</span></div>`}
 document.querySelector('#gardenStreakButton')?.addEventListener('click',open);document.querySelector('#gardenClose')?.addEventListener('click',()=>dialog.close());document.querySelector('#gardenQuickRake')?.addEventListener('click',()=>{if(bridge.startQuick())dialog.close()});
 const avatar=document.querySelector('#dashboardAvatar');if(avatar)new MutationObserver(render).observe(avatar,{attributes:true,attributeFilter:['src']});
 window.KaishiGarden={render,open,preview};render();
})();
