'use strict';
(()=>{
 const bridge=window.KaishiGardenBridge,screen=document.querySelector('#garden');
 if(!bridge||!screen)return;
 const positions={
  'smooth-stone':['18%','72%'],'moss-stone':['72%','66%'],bamboo:['83%','22%'],lantern:['25%','24%'],maple:['72%','18%'],'water-basin':['49%','70%']
 };
 const itemMap=()=>new Map(bridge.items().map(item=>[item.id,item]));
 const localDay=()=>{const now=new Date(),offset=now.getTimezoneOffset();return new Date(now.getTime()-offset*60000).toISOString().slice(0,10)};
 function sceneItems(ids=[]){const items=itemMap();return ids.filter(id=>items.has(id)).map(id=>{const item=items.get(id),position=positions[id]||['50%','50%'];return`<span class="garden-decoration garden-item-${id}" style="--garden-x:${position[0]};--garden-y:${position[1]}" title="${item.name}" aria-label="${item.name}">${item.icon}</span>`}).join('')}
 function avatarActor(avatarSrc,active,shared=false){const action=active?'walking with the garden rake':'sitting quietly before today’s practice';return`<div class="garden-avatar-actor ${active?'walking':'sitting'}" role="img" aria-label="${shared?'Friend’s':'Your'} learner avatar ${action}"><span class="garden-cushion" aria-hidden="true"></span><span class="garden-avatar-body"><img src="${avatarSrc}" alt=""><i class="garden-leg garden-leg-left" aria-hidden="true"></i><i class="garden-leg garden-leg-right" aria-hidden="true"></i></span><span class="garden-rake-tool" aria-hidden="true"><i></i></span></div>`}
 function gardenScene(state,avatarSrc,shared=false){const active=shared?state.activeOn===localDay():Number(state.todayTested||0)>0,leaves=shared?'':Array.from({length:state.behind||0},(_,index)=>`<i class="garden-leaf leaf-${index+1}" aria-hidden="true">🍂</i>`).join('');return`<div class="garden-rake-path ${active?'fresh':''}" aria-hidden="true"></div>${avatarActor(avatarSrc,active,shared)}${sceneItems(state.placed||state.items)}${leaves}`}
 function statusMessage(state){if(state.qualified)return'Today’s pattern is complete. Your learner is still tending the sand.';if(state.todayTested>0)return'Your learner has started walking. Continue today’s Japanese to finish the pattern.';if(state.behind>=2)return'Your learner is resting and the pattern is fading. Practise today to begin restoring it.';if(state.behind===1)return'Your learner is sitting beside a slightly disturbed pattern. Today’s practice will restore it.';return'Your learner is resting. Begin any Japanese practice to set them walking.'}
 function setTab(name='garden'){const garden=name!=='decorate';document.querySelector('#gardenViewPanel').hidden=!garden;document.querySelector('#gardenStorePanel').hidden=garden;document.querySelectorAll('[data-garden-tab]').forEach(button=>button.classList.toggle('active',button.dataset.gardenTab===(garden?'garden':'decorate')));if(garden)render()}
 function render(){const state=bridge.state(),avatar=document.querySelector('#dashboardAvatar')?.src||'media/profiles/guest-learner.webp',miniAvatar=document.querySelector('#gardenMiniAvatar'),streak=document.querySelector('#streak'),miniStatus=document.querySelector('#gardenMiniStatus'),weather=document.querySelector('#gardenMiniWeather'),tokens=document.querySelector('#gardenQuickTokens'),active=state.todayTested>0;if(miniAvatar)miniAvatar.src=avatar;if(streak)streak.textContent=`${state.streak} day${state.streak===1?'':'s'} · Garden streak`;if(miniStatus)miniStatus.textContent=state.qualified?'Garden cared for today':active?'Learner tending the garden':state.behind?`${state.behind} section${state.behind===1?'':'s'} need care`:'Visit your resting learner';if(weather)weather.textContent='🍂'.repeat(state.behind);if(tokens){tokens.querySelectorAll('i').forEach((token,index)=>token.classList.toggle('used',index<state.quickUsed));tokens.setAttribute('aria-label',`${state.quickRemaining} of 2 Quick Rakes available this week`)}
  const intro=document.querySelector('#gardenPageIntro');if(intro)intro.textContent=active?'Your learner is walking the garden with the rake because you practised Japanese today.':'Your learner is resting on the cushion. Begin any Japanese practice and they will start tending the garden.';
  const scene=document.querySelector('#gardenScene');if(scene){scene.innerHTML=gardenScene(state,avatar);scene.className=`garden-scene behind-${state.behind} ${active?'garden-active':'garden-resting'}${state.qualified?' cared':''}`}
  const cards=document.querySelector('#gardenStatusCards');if(cards)cards.innerHTML=`<article><strong>${state.streak}</strong><span>day garden journey</span></article><article><strong>${state.behind}/3</strong><span>sections behind</span></article><article><strong>${state.quickRemaining}/2</strong><span>Quick Rakes left</span></article>`;
  const quick=document.querySelector('#gardenQuickRake'),help=document.querySelector('#gardenQuickHelp');if(quick){quick.disabled=state.qualified||!state.quickRemaining;quick.textContent=state.qualified?'✓ Garden cared for today':state.quickRemaining?`Quick Rake · 3 reviews (${state.quickRemaining} left)`:'Quick Rakes used this week'}if(help)help.textContent=statusMessage(state);
  document.querySelectorAll('#gardenApBalance,#gardenStoreBalance').forEach(balance=>balance.textContent=`${state.availableAp.toLocaleString()} AP`);
  const store=document.querySelector('#gardenStoreGrid');if(store){store.innerHTML=bridge.items().map(item=>{const owned=state.owned.includes(item.id),placed=state.placed.includes(item.id),affordable=state.availableAp>=item.cost;return`<article class="garden-store-item ${owned?'owned':''}"><span aria-hidden="true">${item.icon}</span><div><strong>${item.name}</strong><small>${item.description}</small></div><button type="button" data-garden-item="${item.id}"${!owned&&!affordable?' disabled':''}>${owned?(placed?'Store':'Place'):(item.cost?`${item.cost} AP`:'Free')}</button></article>`}).join('');store.querySelectorAll('[data-garden-item]').forEach(button=>button.onclick=()=>{const result=bridge.buy(button.dataset.gardenItem);if(help)help.textContent=result.message;render()})}
 }
 function open(tab='garden'){render();setTab(tab);if(typeof show==='function')show('garden')}
 function preview(state={},avatarSrc='media/profiles/guest-learner.webp'){const safe={items:Array.isArray(state.items)?state.items:[],streak:Number(state.streak||0),activeOn:String(state.activeOn||'')};return`<div class="friend-garden-scene ${safe.activeOn===localDay()?'garden-active':'garden-resting'}">${gardenScene(safe,avatarSrc,true)}</div><div class="friend-garden-caption"><strong>Garden of Practice</strong><span>${safe.streak} day${safe.streak===1?'':'s'} · ${safe.items.length} decoration${safe.items.length===1?'':'s'}</span></div>`}
 document.querySelector('#gardenStreakButton')?.addEventListener('click',()=>open());document.querySelector('#journeyGarden')?.addEventListener('click',()=>open());document.querySelector('#gardenBack')?.addEventListener('click',()=>show('home'));document.querySelector('#gardenQuickRake')?.addEventListener('click',()=>bridge.startQuick());document.querySelector('#gardenDecorate')?.addEventListener('click',()=>setTab('decorate'));document.querySelectorAll('[data-garden-tab]').forEach(button=>button.addEventListener('click',()=>setTab(button.dataset.gardenTab)));
 const avatar=document.querySelector('#dashboardAvatar');if(avatar)new MutationObserver(render).observe(avatar,{attributes:true,attributeFilter:['src']});
 window.KaishiGarden={render,open,preview};render();
})();
