'use strict';
/* Kaishi Quest v11.17.0 — Japan Ready compatibility. */
(() => {
  const COMMIT='2148988b621f01af1f0f808e2e0b6631bdf6e11f';
  const SOURCE=`https://raw.githubusercontent.com/terryjread-sudo/Kakashi-Web/${COMMIT}/japan-ready.js`;
  const q=s=>document.querySelector(s);
  const isJapan=()=>{try{return window.KaishiJapanReadyBridge?.getMeta?.().activeCampaign==='japan-ready'}catch{return false}};
  function meta(){try{const key=typeof profileStorageKey==='function'?profileStorageKey('kq-meta'):'kq-meta';return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}}
  function save(m){try{const key=typeof profileStorageKey==='function'?profileStorageKey('kq-meta'):'kq-meta';localStorage.setItem(key,JSON.stringify(m))}catch{}}
  function addChooserButtons(){const h=q('#campaignChooser .campaign-chooser-heading');if(!h||q('#chooseJapanReadyCampaign'))return;const a=document.createElement('div');a.className='campaign-choice-actions';a.innerHTML='<button id="chooseJourneyCampaign" type="button">📖 Journey</button><button id="chooseJapanReadyCampaign" type="button">✈️ Japan Ready</button>';h.appendChild(a)}
  function chooseJourney(){const m=meta();m.activeCampaign='journey';m.campaignSelectionExplicit=true;save(m);try{window.KaishiJapanReadyBridge?.save?.()}catch{};q('#journeyCampaignPreview')?.removeAttribute('hidden');q('#japanReadyCampaignPreview')?.setAttribute('hidden','');}
  function chooseJapan(){const m=meta();m.activeCampaign='japan-ready';m.campaignSelectionExplicit=true;save(m)}
  function stabiliseDashboard(){const home=q('#home');if(!home?.classList.contains('active'))return;const m=meta();if(m.campaignSelectionExplicit!==true||m.activeCampaign!=='japan-ready'){m.activeCampaign='journey';save(m)}const j=q('#journeyCampaignPreview'),r=q('#japanReadyCampaignPreview');if(j)j.hidden=false;if(r)r.hidden=true;const title=q('#campaignChooserTitle');if(title)title.textContent='Full Japanese Journey';const text=q('#campaignChooserText');if(text)text.textContent='Follow one gradual path of small lessons. Practice activities appear when they help reinforce what you have learned.'}
  function speak(text){const value=String(text||'').trim();if(!value)return false;if(!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined'){console.warn('Japan Ready: speech synthesis is unavailable');return false}try{const s=window.speechSynthesis;const u=new SpeechSynthesisUtterance(value);u.lang='ja-JP';u.rate=.86;u.pitch=1;const vs=s.getVoices();u.voice=vs.find(v=>/^ja(?:-|_|$)/i.test(v.lang||''))||vs.find(v=>/japanese|kyoko|haruka|nanami|sayaka|ayumi|ichiro|otoya|takumi/i.test(v.name||''))||null;s.resume?.();s.speak(u);setTimeout(()=>{try{if(s.paused)s.resume()}catch{}},120);setTimeout(()=>{try{if(!s.speaking&&!s.paused)s.speak(u)}catch{}},220);return true}catch(e){console.warn('Japan Ready audio error',e);return false}}
  function installAudio(){if(document.documentElement.dataset.kq17Audio)return;document.documentElement.dataset.kq17Audio='1';let last=null,lastAt=0;const handle=e=>{const b=e.target?.closest?.('.cheat-audio,[data-cheat-audio]');if(!b)return;const text=b.getAttribute('data-cheat-audio')||b.dataset?.japanese||'';if(!text)return;const now=Date.now();if(last===b&&now-lastAt<500)return;last=b;lastAt=now;if(!isJapan() && !q('#japanReadyCheatSheet')?.classList.contains('active'))return;e.preventDefault();e.stopImmediatePropagation();speak(text)};document.addEventListener('pointerdown',handle,true);document.addEventListener('click',handle,true)}
  function run(){addChooserButtons();installAudio();document.addEventListener('click',e=>{if(e.target.closest?.('#chooseJourneyCampaign'))chooseJourney();if(e.target.closest?.('#chooseJapanReadyCampaign'))chooseJapan()},true);const home=q('#home');if(home)new MutationObserver(()=>{clearTimeout(window.__kq17Camp);window.__kq17Camp=setTimeout(stabiliseDashboard,0)}).observe(home,{subtree:true,childList:true,attributes:true,attributeFilter:['class','hidden']});stabiliseDashboard();window.addEventListener('pageshow',stabiliseDashboard);try{if('speechSynthesis'in window)speechSynthesis.getVoices()}catch{}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
  fetch(SOURCE,{cache:'no-store'}).then(r=>r.ok?r.text():Promise.reject(new Error(`HTTP ${r.status}`))).then(src=>{src=src.replace("$('#chooseJourneyCampaign').onclick=()=>setMode('journey');","$('#chooseJourneyCampaign')?.addEventListener('click',()=>setMode('journey'));").replace("$('#chooseJapanReadyCampaign').onclick=()=>setMode('japan-ready');","$('#chooseJapanReadyCampaign')?.addEventListener('click',()=>setMode('japan-ready'));");const s=document.createElement('script');s.textContent=src;document.head.appendChild(s);setTimeout(()=>{installAudio();stabiliseDashboard()},50)}).catch(e=>console.error('Japan Ready loader failed',e));
})();
