'use strict';
let cards={},selected='';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){cards=await fetch('visual-mnemonics.json?v=4.1.0').then(r=>r.json());const drafts=JSON.parse(localStorage.getItem('kq-vms-drafts')||'{}');cards={...cards,...drafts};renderList();select(Object.keys(cards)[0])}
function renderList(q=''){const x=q.toLowerCase();$('#list').innerHTML=Object.entries(cards).filter(([k,v])=>`${k} ${v.meaning}`.toLowerCase().includes(x)).map(([k,v])=>`<button data-key="${esc(k)}"><b>${esc(v.word)}</b> ${esc(v.reading)} — ${esc(v.meaning)}</button>`).join('');document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>select(b.dataset.key))}
function select(k){selected=k;const v=cards[k];if(!v)return;$('#word').value=v.word;$('#reading').value=v.reading;$('#meaning').value=v.meaning;$('#sound').value=v.soundMnemonic;$('#story').value=v.story;$('#opacity').value=v.overlayOpacity||.32;preview()}
function preview(){const v={...cards[selected],meaning:$('#meaning').value,soundMnemonic:$('#sound').value,story:$('#story').value,overlayOpacity:+$('#opacity').value};$('#preview').innerHTML=`<section class="vms-card"><div class="vms-scene"><img src="${esc(v.scene)}"><div class="vms-overlay show" style="--overlay-opacity:${v.overlayOpacity}">${esc(v.overlay)}</div></div><div class="vms-reading-panel show"><div><span>Hiragana</span><strong>${esc(v.reading)}</strong></div><div><span>Katakana</span><strong>${esc(v.katakana)}</strong></div><div><span>Romaji</span><strong>${esc(v.romaji)}</strong></div></div><div class="vms-memory show"><p><span>Sounds like</span><strong>${esc(v.soundMnemonic)}</strong></p><p><span>Story</span>${esc(v.story)}</p></div></section>`}
function save(){cards[selected]={...cards[selected],meaning:$('#meaning').value,soundMnemonic:$('#sound').value,story:$('#story').value,overlayOpacity:+$('#opacity').value};localStorage.setItem('kq-vms-drafts',JSON.stringify(cards));preview()}
function exp(){save();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(cards,null,2)],{type:'application/json'}));a.download='visual-mnemonics.json';a.click();URL.revokeObjectURL(a.href)}
$('#search').oninput=e=>renderList(e.target.value);['meaning','sound','story','opacity'].forEach(id=>$('#'+id).oninput=preview);$('#save').onclick=save;$('#export').onclick=exp;init();