'use strict';
let cards={},selected='';const DRAFT_KEY='kq-vms-drafts-v46';const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){const source=await fetch('visual-mnemonics.json?v=5.3.0',{cache:'no-store'}).then(r=>r.json());const drafts=JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}');cards={...source,...drafts};renderList();updateSummary();select(Object.keys(cards)[0])}
function statusOf(v){return v.imageStatus==='needs-regeneration'||v.status==='needs-regeneration'?'needs-regeneration':'approved'}
function updateSummary(){const counts={approved:0,'needs-regeneration':0,'pending-review':0};Object.values(cards).forEach(v=>counts[statusOf(v)]=(counts[statusOf(v)]||0)+1);$('#summary').innerHTML=`<span>✓ ${counts.approved||0} approved</span><span>↻ ${counts['needs-regeneration']||0} need regeneration</span><span>⏳ ${counts['pending-review']||0} pending</span>`}
function renderList(){const q=$('#search').value.toLowerCase(),filter=$('#filter').value;$('#list').innerHTML=Object.entries(cards).filter(([k,v])=>`${k} ${v.meaning}`.toLowerCase().includes(q)).filter(([,v])=>filter==='all'||statusOf(v)===filter).map(([k,v])=>`<button data-key="${esc(k)}"><b>${esc(v.word)}</b> ${esc(v.reading)} — ${esc(v.meaning)}<span class="studio-item-status">${statusOf(v)==='approved'?'✓ Approved':statusOf(v)==='needs-regeneration'?'↻ Needs regeneration':'⏳ Pending review'}</span></button>`).join('');document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>select(b.dataset.key))}
function select(k){selected=k;const v=cards[k];if(!v)return;$('#word').value=v.word;$('#reading').value=v.reading;$('#meaning').value=v.meaning;$('#sound').value=v.soundMnemonic;$('#story').value=v.story;$('#note').value=v.reviewNote||'';$('#opacity').value=v.overlayOpacity??1;$('#overlaySize').value=v.overlaySize??1;syncOutputs();showStatus();preview()}
function formData(){const v=cards[selected];return {...v,meaning:$('#meaning').value,soundMnemonic:$('#sound').value,story:$('#story').value,reviewNote:$('#note').value,overlayOpacity:+$('#opacity').value,overlaySize:+$('#overlaySize').value}}
function syncOutputs(){$('#opacityValue').value=(+$('#opacity').value).toFixed(2);$('#overlaySizeValue').value=(+$('#overlaySize').value).toFixed(2)}
function showStatus(){const s=statusOf(cards[selected]),box=$('#status');box.className=`status status-${s}`;box.textContent=s==='approved'?'✓ Approved: available in the main app':s==='needs-regeneration'?'↻ Flagged: hidden from the main app':'⏳ Pending review: hidden from the main app'}
function preview(){if(!selected)return;syncOutputs();const v=formData();$('#preview').innerHTML=`<section class="vms-card"><div class="vms-scene"><img src="${esc(v.scene)}?v=${Number(v.imageVersion)||1}" alt="Preview"><div class="vms-overlay show" style="--overlay-opacity:${v.overlayOpacity};--overlay-size:${v.overlaySize};--overlay-colour:${esc(v.overlayColour||'#fff')}">${esc(v.overlay)}</div></div><div class="vms-reading-panel show"><div><span>Hiragana</span><strong>${esc(v.reading)}</strong></div><div><span>Katakana</span><strong>${esc(v.katakana)}</strong></div><div><span>Romaji</span><strong>${esc(v.romaji)}</strong></div></div><div class="vms-memory show"><p><span>Sounds like</span><strong>${esc(v.soundMnemonic)}</strong></p><p><span>Story</span>${esc(v.story)}</p></div></section>`}
function persist(){if(!selected)return;cards[selected]=formData();localStorage.setItem(DRAFT_KEY,JSON.stringify(cards));updateSummary();renderList();showStatus();preview()}
function nextPendingKey(current){const keys=Object.keys(cards),start=Math.max(0,keys.indexOf(current));for(let step=1;step<=keys.length;step++){const key=keys[(start+step)%keys.length];if(statusOf(cards[key])==='pending-review')return key}return ''}
function setStatus(status){const decided=selected;cards[selected]=formData();cards[selected].imageStatus=status;cards[selected].status=status;if(status==='approved'){cards[selected].approvedAt=new Date().toISOString().slice(0,10);cards[selected].reviewNote=$('#note').value||'Approved in Mnemonic Studio.'}else{delete cards[selected].approvedAt;cards[selected].reviewNote=$('#note').value||'Regenerate this image.'}localStorage.setItem(DRAFT_KEY,JSON.stringify(cards));updateSummary();renderList();const next=nextPendingKey(decided);if(next){select(next);document.querySelector(`[data-key=\"${CSS.escape(next)}\"]`)?.scrollIntoView({block:'nearest'})}else{$('#status').className='status status-approved';$('#status').textContent='✓ Review complete — no pending images remain.';preview()}}
function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#search').oninput=renderList;$('#filter').onchange=renderList;['meaning','sound','story','note','opacity','overlaySize'].forEach(id=>$('#'+id).oninput=preview);$('#save').onclick=persist;$('#approve').onclick=()=>setStatus('approved');$('#regenerate').onclick=()=>setStatus('needs-regeneration');$('#studyPreview').onclick=()=>{persist();const u=new URL('study-preview.html',location.href);u.searchParams.set('key',selected);window.open(u,'_blank')};$('#export').onclick=()=>{persist();download('visual-mnemonics.json',cards)};$('#exportQueue').onclick=()=>{persist();download('mnemonic-regeneration-queue.json',Object.fromEntries(Object.entries(cards).filter(([,v])=>statusOf(v)==='needs-regeneration')))};init();
