'use strict';
(()=>{
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 let dialog,stream,recorder,recognition,audioContext,analyser,waveFrame,chunks=[],transcript='',active=null,objectUrl='',recognitionDone=false,recordingReady=false,resultsShown=false,resultTimer=0,recognitionError='',practiceMode='full',practiceSteps=[],practiceForms=[],activeStep=0,completedSteps=new Set();
 const digitKanji={'0':'零','1':'一','2':'二','3':'三','4':'四','5':'五','6':'六','7':'七','8':'八','9':'九'};
 const normalise=value=>String(value||'').toLowerCase().normalize('NFKC').replace(/[ァ-ヶ]/g,character=>String.fromCharCode(character.charCodeAt(0)-96)).replace(/[0-9]/g,digit=>digitKanji[digit]).replace(/[\s。、！？!?.,・「」『』（）()\-ー]/g,'');
 const splitKeywords=value=>String(value||'').replace(/[、。！？!?]/g,'').split(/(?:から|まで|って|では|には|は|が|を|に|で|と|も|へ|の|\s+)/).map(item=>item.trim()).filter(item=>item.length>1);
 const chunkPhrase=value=>{
  const cleaned=String(value||'').trim().replace(/[。！？!?]+$/,'');
  let parts=cleaned.split(/[、。，,／/]|\s{2,}/).flatMap(clause=>{
   let marked=clause.trim().replace(/(.*?[\p{Script=Han}\p{Script=Katakana}々0-9](?:では|には|から|まで|って|より|ので|のに|なら|は|が|を|に|で|と|も|へ))(?=.)/gu,'$1|');
   marked=marked.replace(/(?=(?:お願いします|ください|ありません|あります|でしょう|だと思います)$)/,'|');
   return marked.split('|').map(item=>item.trim()).filter(Boolean);
  });
  for(let index=parts.length-1;index>0;index--){if(parts[index].length<2){parts[index-1]+=parts[index];parts.splice(index,1)}}
  if(parts.length>5)parts=[...parts.slice(0,4),parts.slice(4).join('')];
  return parts.length>1?parts:[cleaned];
 };
 const keywordList=options=>{
  const supplied=(options.keywords||[]).map(item=>typeof item==='string'?{label:item,forms:[item]}:{label:item.label||item.forms?.[0],forms:item.forms||[item.label]}).filter(item=>item.label);
  if(supplied.length)return supplied.slice(0,5);
  const cleaned=String(options.phrase||'').replace(/[、。！？!?]/g,''),phrase=splitKeywords(cleaned),reading=splitKeywords(options.reading);
  return (phrase.length?phrase:[cleaned]).slice(0,4).map((label,index)=>({label,forms:[label,reading[index]].filter(Boolean)}));
 };
 function ensureDialog(){
  if(dialog)return dialog;
  dialog=document.createElement('dialog');dialog.className='pronunciation-coach-dialog';dialog.id='pronunciationCoachDialog';
  dialog.innerHTML=`<section class="pronunciation-coach"><header class="pronunciation-head"><img src="media/guides/sensei/sensei-analysing.webp" alt="Sensei analysing your practice"><div><span class="eyebrow">Optional speaking practice</span><h2>Pronunciation Coach</h2><p>Build it gradually, then say it naturally.</p></div><button class="pronunciation-close" aria-label="Close">×</button></header><div class="pronunciation-mode" role="group" aria-label="Pronunciation practice style"><button type="button" data-pronunciation-mode="chunks">🧩 Build in chunks</button><button type="button" data-pronunciation-mode="full">💬 Whole sentence</button></div><nav class="pronunciation-chunk-track" aria-label="Sentence practice steps"></nav><section class="pronunciation-phrase"><b class="pronunciation-step-label"></b><strong id="pronunciationPhrase" lang="ja"></strong><small id="pronunciationReading"></small><span id="pronunciationWhole" lang="ja"></span><span id="pronunciationMeaning"></span></section><canvas class="pronunciation-wave" width="560" height="76" aria-label="Live microphone waveform"></canvas><div class="pronunciation-status" aria-live="polite">Hear the model, then record one natural attempt.</div><div class="pronunciation-actions"><button class="pronunciation-model audio">🔊 Hear this part</button><button class="pronunciation-record primary">🎙️ Start recording</button></div><section class="pronunciation-results" hidden><div class="pronunciation-transcript"><b>What the device heard</b><p></p></div><div class="pronunciation-keywords"></div><p class="pronunciation-guidance"></p><audio controls></audio><button type="button" class="pronunciation-next primary" hidden></button></section><small class="pronunciation-privacy">Your recording stays on this device and is discarded when this coach closes. Speech recognition availability depends on your browser.</small></section>`;
  document.body.append(dialog);dialog.querySelector('.pronunciation-close').onclick=close;dialog.addEventListener('close',cleanup);dialog.querySelector('.pronunciation-model').onclick=()=>speakJapanese(targetPhrase());dialog.querySelector('.pronunciation-record').onclick=toggle;dialog.querySelector('.pronunciation-next').onclick=nextPracticeStep;dialog.querySelectorAll('[data-pronunciation-mode]').forEach(button=>button.onclick=()=>setPracticeMode(button.dataset.pronunciationMode));
  return dialog;
 }
 function targetPhrase(){return practiceMode==='chunks'&&activeStep<practiceSteps.length?practiceSteps[activeStep]:active?.phrase||''}
 function resetAttempt(){cleanup();transcript='';recognitionError='';dialog.querySelector('.pronunciation-results').hidden=true;dialog.querySelector('.pronunciation-next').hidden=true;dialog.querySelector('.pronunciation-record').textContent='🎙️ Start recording';dialog.querySelector('.pronunciation-record').classList.remove('recording')}
 function renderPractice(){
  const chunksAvailable=practiceSteps.length>1,isFinal=practiceMode==='chunks'&&activeStep===practiceSteps.length,target=targetPhrase();
  dialog.querySelector('[data-pronunciation-mode="chunks"]').hidden=!chunksAvailable;
  dialog.querySelectorAll('[data-pronunciation-mode]').forEach(button=>{const selected=button.dataset.pronunciationMode===practiceMode;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected))});
  const track=dialog.querySelector('.pronunciation-chunk-track');track.hidden=practiceMode!=='chunks'||!chunksAvailable;track.innerHTML=practiceSteps.map((part,index)=>`<button type="button" data-pronunciation-step="${index}" class="${index===activeStep?'active ':''}${completedSteps.has(index)?'complete':''}" aria-label="Practise chunk ${index+1}: ${part}"${index===activeStep?' aria-current="step"':''}>${completedSteps.has(index)?'✓':index+1}<small lang="ja">${part}</small></button>`).join('')+`<button type="button" data-pronunciation-step="${practiceSteps.length}" class="final ${isFinal?'active ':''}${completedSteps.has('full')?'complete':''}" aria-label="Practise the complete sentence"${isFinal?' aria-current="step"':''}>${completedSteps.has('full')?'✓':'★'}<small>All together</small></button>`;
  track.querySelectorAll('[data-pronunciation-step]').forEach(button=>button.onclick=()=>selectPracticeStep(Number(button.dataset.pronunciationStep)));
  dialog.querySelector('.pronunciation-step-label').textContent=practiceMode==='full'?'Whole sentence':isFinal?'Final step · all together':`Chunk ${activeStep+1} of ${practiceSteps.length}`;
  dialog.querySelector('#pronunciationPhrase').textContent=target;
  dialog.querySelector('#pronunciationReading').textContent=active?.reading?(practiceMode==='chunks'&&!isFinal?`Full reading: ${active.reading}`:active.reading):'';
  const whole=dialog.querySelector('#pronunciationWhole');whole.textContent=practiceMode==='chunks'&&!isFinal?`Complete sentence: ${active?.phrase||''}`:'';whole.hidden=!whole.textContent;
  dialog.querySelector('#pronunciationMeaning').textContent=active?.meaning||'';
  dialog.querySelector('.pronunciation-model').textContent=practiceMode==='chunks'&&!isFinal?'🔊 Hear this chunk':'🔊 Hear full sentence';
 }
 function selectPracticeStep(index){if(recorder?.state==='recording')return;resetAttempt();practiceMode='chunks';activeStep=Math.max(0,Math.min(index,practiceSteps.length));renderPractice();setStatus(activeStep===practiceSteps.length?'Now connect every chunk into one natural sentence.':'Hear this short chunk, then record yourself saying it.')}
 function setPracticeMode(mode){if(recorder?.state==='recording'||(mode==='chunks'&&practiceSteps.length<2))return;resetAttempt();practiceMode=mode;activeStep=mode==='chunks'?0:practiceSteps.length;renderPractice();setStatus(mode==='chunks'?'Start small: hear chunk 1, then record it.':'Hear the model, then record the complete sentence.')}
 function nextPracticeStep(){if(practiceMode!=='chunks')return;selectPracticeStep(Math.min(activeStep+1,practiceSteps.length))}
 function setStatus(message,kind=''){const node=dialog.querySelector('.pronunciation-status');node.textContent=message;node.className=`pronunciation-status ${kind}`.trim()}
 function draw(){if(!analyser)return;const canvas=dialog.querySelector('canvas'),ctx=canvas.getContext('2d'),data=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(data);ctx.fillStyle='#0f172a';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.lineWidth=3;ctx.strokeStyle='#5eead4';ctx.beginPath();data.forEach((value,index)=>{const x=index/(data.length-1)*canvas.width,y=value/128*canvas.height/2;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();waveFrame=requestAnimationFrame(draw)}
 function recognitionResult(event){transcript=Array.from(event.results).map(result=>result[0]?.transcript||'').filter(Boolean).join(' ').trim();if(transcript)setStatus(`Japanese detected: ${transcript}`,'listening')}
 function finishResultsWhenReady(){if(resultsShown||!recordingReady||(!recognitionDone&&Recognition))return;clearTimeout(resultTimer);showResults()}
 async function start(){
  try{setStatus('Waiting for Chrome’s microphone permission…','listening');stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];transcript='';recognitionError='';recognitionDone=!Recognition;recordingReady=false;resultsShown=false;clearTimeout(resultTimer);const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(type=>window.MediaRecorder?.isTypeSupported?.(type));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=()=>{recordingReady=true;finishResultsWhenReady()};recorder.start();audioContext=new (window.AudioContext||window.webkitAudioContext)();analyser=audioContext.createAnalyser();analyser.fftSize=256;audioContext.createMediaStreamSource(stream).connect(analyser);draw();if(Recognition){recognition=new Recognition();recognition.lang='ja-JP';recognition.interimResults=true;recognition.continuous=true;recognition.onresult=recognitionResult;recognition.onerror=event=>{recognitionError=event.error||'recognition-error'};recognition.onend=()=>{recognitionDone=true;finishResultsWhenReady()};try{recognition.start()}catch(error){recognitionError='start-failed';recognitionDone=true}}dialog.querySelector('.pronunciation-record').textContent='■ Stop and review';dialog.querySelector('.pronunciation-record').classList.add('recording');setStatus('Listening for Japanese… speak once, then wait for the detected words to appear.','listening')}
  catch(error){stream?.getTracks().forEach(track=>track.stop());audioContext?.close?.();stream=audioContext=analyser=null;setStatus('Microphone access is unavailable. You can still hear and shadow the model.','review')}
 }
 function stop(){try{recognition?.stop()}catch{};if(recorder?.state==='recording')recorder.stop();cancelAnimationFrame(waveFrame);analyser=null;audioContext?.close?.();dialog.querySelector('.pronunciation-record').textContent='🎙️ Try again';dialog.querySelector('.pronunciation-record').classList.remove('recording');setStatus('Finishing Japanese detection…','review');clearTimeout(resultTimer);resultTimer=setTimeout(()=>{recognitionDone=true;finishResultsWhenReady()},4000)}
 function toggle(){recorder?.state==='recording'?stop():start()}
 function showResults(){
  if(resultsShown)return;resultsShown=true;
  stream?.getTracks().forEach(track=>track.stop());
  const results=dialog.querySelector('.pronunciation-results'),heard=normalise(transcript),practisingChunk=practiceMode==='chunks'&&activeStep<practiceSteps.length,keywords=practisingChunk?[{label:targetPhrase(),forms:practiceForms[activeStep]||[targetPhrase()]}]:keywordList(active),matches=keywords.map(keyword=>({...keyword,heard:keyword.forms.some(form=>heard.includes(normalise(form)))})),missing=matches.filter(item=>!item.heard);
  if(!missing.length&&transcript.trim())completedSteps.add(practisingChunk?activeStep:'full');renderPractice();
  results.hidden=false;results.querySelector('.pronunciation-transcript p').textContent=transcript.trim()||(Recognition?recognitionError==='no-speech'?'Chrome did not hear speech. Move closer to the microphone and try again.':'No clear Japanese transcript was returned. Listen to your recording and try once more.':'Speech recognition is not supported here; use playback to compare rhythm and pauses.');results.querySelector('.pronunciation-keywords').innerHTML=matches.map(item=>`<span class="pronunciation-keyword ${item.heard?'heard':''}">${item.heard?'✓ Heard':'Try again'} · ${item.label}</span>`).join('');results.querySelector('.pronunciation-guidance').textContent=!Recognition?'Focus on matching the model’s rhythm, pauses and vowel length.':missing.length?`Try once more, giving extra space and clarity to: ${missing.map(item=>item.label).join('、')}.`:practisingChunk?'This chunk was detected. Compare its rhythm with the model, then continue to the next part.':'All important phrases were detected. Now compare your rhythm and vowel length with the model.';
  const audio=results.querySelector('audio');if(objectUrl)URL.revokeObjectURL(objectUrl);if(chunks.length){objectUrl=URL.createObjectURL(new Blob(chunks,{type:recorder?.mimeType||'audio/webm'}));audio.src=objectUrl;audio.hidden=false}else audio.hidden=true;
  const next=results.querySelector('.pronunciation-next');next.hidden=practiceMode!=='chunks'||activeStep===practiceSteps.length;next.textContent=activeStep===practiceSteps.length-1?'Put it all together →':'Next chunk →';
 }
 function cleanup(){resultsShown=true;clearTimeout(resultTimer);if(recorder?.state==='recording')recorder.stop();try{recognition?.abort()}catch{};stream?.getTracks().forEach(track=>track.stop());cancelAnimationFrame(waveFrame);analyser=null;audioContext?.close?.();if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl='';recorder=recognition=stream=audioContext=null}
 function close(){cleanup();dialog?.close()}
 function open(options){ensureDialog();cleanup();active={phrase:options.phrase||'',reading:options.reading||'',meaning:options.meaning||'',keywords:options.keywords||[]};const suppliedChunks=Array.isArray(options.chunks)?options.chunks.filter(Boolean):[],prepared=(suppliedChunks.length?suppliedChunks:chunkPhrase(active.phrase)).map(item=>typeof item==='string'?{text:item,forms:[item]}:{text:item.text||item.label||'',forms:[item.text||item.label,item.reading,...(item.forms||[])].filter(Boolean)}).filter(item=>item.text);practiceSteps=prepared.map(item=>item.text);practiceForms=prepared.map(item=>item.forms);practiceMode=practiceSteps.length>1?'chunks':'full';activeStep=practiceMode==='chunks'?0:practiceSteps.length;completedSteps=new Set();dialog.querySelector('.pronunciation-results').hidden=true;dialog.querySelector('.pronunciation-record').textContent='🎙️ Start recording';dialog.querySelector('.pronunciation-record').classList.remove('recording');renderPractice();setStatus(Recognition?(practiceMode==='chunks'?'Start small: hear chunk 1, then record it.':'Hear the model, then record one natural attempt.'):'This browser can record playback practice, but cannot return a Japanese transcript.');if(!dialog.open)dialog.showModal()}
 function addLaunch(container,extract,label='🎙️ Practise pronunciation'){
  if(!container||container.querySelector(':scope > .pronunciation-launch'))return;const button=document.createElement('button');button.type='button';button.className='pronunciation-launch';button.textContent=label;button.onclick=()=>open(extract());container.append(button)
 }
 function mountLaunchers(){
  document.querySelectorAll('.sl-intro').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('.sl-main-sentence')?.textContent,reading:card.querySelector('.sl-reading')?.textContent,meaning:card.querySelector('.sl-meaning')?.textContent,chunks:[...(card.parentElement?.querySelectorAll('.sl-breakdown .sl-chunk')||[])].map(node=>({text:node.querySelector('strong')?.textContent.trim(),reading:node.querySelector('small')?.textContent.trim()})).filter(item=>item.text)})));
  document.querySelectorAll('.theatre-shadow-card').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('p[lang="ja"]')?.textContent,reading:card.querySelector('small')?.textContent,meaning:card.querySelector('strong')?.textContent}),'🎙️ Coach important phrases'));
  document.querySelectorAll('.conversation-correct').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('strong[lang="ja"]')?.textContent,reading:card.querySelector('small')?.textContent,meaning:card.querySelector('p')?.textContent})));
  document.querySelectorAll('.manga-reading-card').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('.manga-japanese')?.textContent,reading:card.querySelector('.manga-reading')?.textContent,meaning:'Dialogue from this manga panel'}),'🎙️ Say this panel'));
 }
 const launchObserver=new MutationObserver(mountLaunchers);launchObserver.observe(document.documentElement,{childList:true,subtree:true});
 window.KaishiPronunciation={open,available:Boolean(navigator.mediaDevices?.getUserMedia),recognitionAvailable:Boolean(Recognition)};mountLaunchers();
})();
