'use strict';
(()=>{
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 let dialog,stream,recorder,recognition,audioContext,analyser,waveFrame,chunks=[],transcript='',active=null,objectUrl='',recognitionDone=false,recordingReady=false,resultsShown=false,resultTimer=0,recognitionStopTimer=0,autoStopTimer=0,recognitionError='',practiceMode='full',captureMode=Recognition?'recognition':'recording',practiceSteps=[],practiceForms=[],activeStep=0,completedSteps=new Set(),recordingStartedAt=0,lastVoiceAt=0,voiceStarted=false,voiceFrames=0,stopStarted=false,attemptActive=false;
 const VOICE_THRESHOLD=.035,SILENCE_STOP_MS=1100,MAX_RECORDING_MS=10000,RECOGNITION_GRACE_MS=900;
 const digitKanji={'0':'零','1':'一','2':'二','3':'三','4':'四','5':'五','6':'六','7':'七','8':'八','9':'九'};
 try{localStorage.removeItem('kq-pronunciation-diagnostics-v1')}catch{}
 const normalise=value=>String(value||'').toLowerCase().normalize('NFKC').replace(/[ァ-ヶ]/g,character=>String.fromCharCode(character.charCodeAt(0)-96)).replace(/[0-9]/g,digit=>digitKanji[digit]).replace(/[\s。、！？!?.,・「」『』（）()\-ー]/g,'');
 const splitKeywords=value=>String(value||'').replace(/[、。！？!?]/g,'').split(/(?:から|まで|って|では|には|は|が|を|に|で|と|も|へ|の|\s+)/).map(item=>item.trim()).filter(item=>item.length>1);
 const chunkPhrase=value=>{
  const cleaned=String(value||'').trim().replace(/[。！？!?]+$/,'');
  let parts=cleaned.split(/[、。，,／/]|\s{2,}/).flatMap(clause=>{
   let marked=clause.trim().replace(/(.*?[\p{Script=Han}\p{Script=Katakana}々0-9](?:では|には|から|まで|って|より|ので|のに|なら|は|が|を|に|で|と|も|へ))(?=.)/gu,'$1|');
   marked=marked.replace(/(?=(?:お願いします|ください|ありません|あります|でしょう|だと思います)$)/,'|');
   return marked.split('|').map(item=>item.trim()).filter(Boolean);
  });
  for(let index=parts.length-1;index>0;index--){if(parts[index].length<2){parts[index-1]+=parts[index];parts.splice(index,1)}}
  if(parts.length>5)parts=[...parts.slice(0,4),parts.slice(4).join('')];
  return parts.length>1?parts:[cleaned];
 };
 const keywordList=options=>{
  const supplied=(options.keywords||[]).map(item=>typeof item==='string'?{label:item,forms:[item]}:{label:item.label||item.forms?.[0],forms:item.forms||[item.label]}).filter(item=>item.label);
  if(supplied.length)return supplied.slice(0,5);
  const cleaned=String(options.phrase||'').replace(/[、。！？!?]/g,''),phrase=splitKeywords(cleaned),reading=splitKeywords(options.reading);
  return (phrase.length?phrase:[cleaned]).slice(0,4).map((label,index)=>({label,forms:[label,reading[index]].filter(Boolean)}));
 };
 function ensureDialog(){
  if(dialog)return dialog;
  dialog=document.createElement('dialog');dialog.className='pronunciation-coach-dialog';dialog.id='pronunciationCoachDialog';
  dialog.innerHTML=`<section class="pronunciation-coach"><header class="pronunciation-head"><img src="media/guides/sensei/sensei-analysing.webp" alt="Sensei analysing your practice"><div><span class="eyebrow">Optional speaking practice</span><h2>Pronunciation Coach</h2><p>Build it gradually, then say it naturally.</p></div><button class="pronunciation-close" aria-label="Close">×</button></header><div class="pronunciation-capture-mode" role="group" aria-label="Pronunciation feedback method"><button type="button" data-pronunciation-capture="recognition"><strong>🈶 Check my Japanese</strong><small>Browser recognition · no local recording</small></button><button type="button" data-pronunciation-capture="recording"><strong>🎧 Record & compare</strong><small>Private playback · no transcript</small></button></div><div class="pronunciation-mode" role="group" aria-label="Pronunciation practice style"><button type="button" data-pronunciation-mode="chunks">🧩 Build in chunks</button><button type="button" data-pronunciation-mode="full">💬 Whole sentence</button></div><nav class="pronunciation-chunk-track" aria-label="Sentence practice steps"></nav><section class="pronunciation-phrase"><b class="pronunciation-step-label"></b><strong id="pronunciationPhrase" lang="ja"></strong><small id="pronunciationReading"></small><span id="pronunciationWhole" lang="ja"></span><span id="pronunciationMeaning"></span></section><canvas class="pronunciation-wave" width="560" height="76" aria-label="Live microphone waveform"></canvas><div class="pronunciation-status" aria-live="polite">Hear the model, then make one natural attempt.</div><div class="pronunciation-actions"><button class="pronunciation-model audio">🔊 Hear this part</button><button class="pronunciation-record primary">🎙️ Check my Japanese</button></div><section class="pronunciation-results" hidden><aside class="pronunciation-sensei-feedback" aria-live="polite"><img src="media/guides/sensei/sensei-analysing.webp" alt="Sensei giving pronunciation feedback"><div><strong>Sensei’s feedback</strong><p class="pronunciation-guidance"></p></div></aside><div class="pronunciation-transcript"><b>What the device heard</b><p></p></div><div class="pronunciation-keywords"></div><audio controls></audio><button type="button" class="pronunciation-next primary" hidden></button></section><small class="pronunciation-privacy"></small></section>`;
  document.body.append(dialog);dialog.querySelector('.pronunciation-close').onclick=close;dialog.addEventListener('close',cleanup);dialog.querySelector('.pronunciation-model').onclick=()=>speakJapanese(targetPhrase());dialog.querySelector('.pronunciation-record').onclick=toggle;dialog.querySelector('.pronunciation-next').onclick=nextPracticeStep;dialog.querySelectorAll('[data-pronunciation-mode]').forEach(button=>button.onclick=()=>setPracticeMode(button.dataset.pronunciationMode));dialog.querySelectorAll('[data-pronunciation-capture]').forEach(button=>button.onclick=()=>setCaptureMode(button.dataset.pronunciationCapture));
  return dialog;
 }
 function targetPhrase(){return practiceMode==='chunks'&&activeStep<practiceSteps.length?practiceSteps[activeStep]:active?.phrase||''}
 function captureButtonLabel(){return captureMode==='recognition'?'🎙️ Check my Japanese':'🎙️ Start recording'}
 function captureReadyStatus(){if(captureMode==='recognition')return Recognition?'Chrome or Safari will listen directly for one Japanese phrase.':'Speech recognition is unavailable here. Use Record & compare instead.';return'Your recording stays private and will stop after you finish speaking.'}
 function resetAttempt(){cleanup();transcript='';recognitionError='';dialog.querySelector('.pronunciation-results').hidden=true;dialog.querySelector('.pronunciation-next').hidden=true;dialog.querySelector('.pronunciation-record').textContent=captureButtonLabel();dialog.querySelector('.pronunciation-record').classList.remove('recording');dialog.querySelector('.pronunciation-record').disabled=false}
 function renderCaptureMode(){dialog.querySelectorAll('[data-pronunciation-capture]').forEach(button=>{const selected=button.dataset.pronunciationCapture===captureMode;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected));if(button.dataset.pronunciationCapture==='recognition')button.disabled=!Recognition});dialog.querySelector('.pronunciation-wave').hidden=captureMode!=='recording';dialog.querySelector('.pronunciation-record').textContent=captureButtonLabel();dialog.querySelector('.pronunciation-privacy').textContent=captureMode==='recognition'?'Your browser’s speech service processes this attempt. Kaishi Quest does not store its audio or transcript.':'Audio stays on this device and is discarded when the coach closes. No speech service receives it.'}
 function setCaptureMode(mode){if(attemptActive||mode===captureMode||mode==='recognition'&&!Recognition)return;resetAttempt();captureMode=mode;renderCaptureMode();setStatus(captureReadyStatus())}
 function renderPractice(){
  const chunksAvailable=practiceSteps.length>1,isFinal=practiceMode==='chunks'&&activeStep===practiceSteps.length,target=targetPhrase();
  dialog.querySelector('.pronunciation-mode').hidden=Boolean(active?.compact);dialog.querySelector('[data-pronunciation-mode="chunks"]').hidden=!chunksAvailable;
  dialog.querySelectorAll('[data-pronunciation-mode]').forEach(button=>{const selected=button.dataset.pronunciationMode===practiceMode;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected))});
  const track=dialog.querySelector('.pronunciation-chunk-track');track.hidden=practiceMode!=='chunks'||!chunksAvailable;track.innerHTML=practiceSteps.map((part,index)=>`<button type="button" data-pronunciation-step="${index}" class="${index===activeStep?'active ':''}${completedSteps.has(index)?'complete':''}" aria-label="Practise chunk ${index+1}: ${part}"${index===activeStep?' aria-current="step"':''}>${completedSteps.has(index)?'✓':index+1}<small lang="ja">${part}</small></button>`).join('')+`<button type="button" data-pronunciation-step="${practiceSteps.length}" class="final ${isFinal?'active ':''}${completedSteps.has('full')?'complete':''}" aria-label="Practise the complete sentence"${isFinal?' aria-current="step"':''}>${completedSteps.has('full')?'✓':'★'}<small>All together</small></button>`;
  track.querySelectorAll('[data-pronunciation-step]').forEach(button=>button.onclick=()=>selectPracticeStep(Number(button.dataset.pronunciationStep)));
  dialog.querySelector('.pronunciation-step-label').textContent=active?.compact?'Practise this word':practiceMode==='full'?'Whole sentence':isFinal?'Final step · all together':`Chunk ${activeStep+1} of ${practiceSteps.length}`;
  dialog.querySelector('#pronunciationPhrase').textContent=target;
  dialog.querySelector('#pronunciationReading').textContent=active?.reading?(practiceMode==='chunks'&&!isFinal?`Full reading: ${active.reading}`:active.reading):'';
  const whole=dialog.querySelector('#pronunciationWhole');whole.textContent=practiceMode==='chunks'&&!isFinal?`Complete sentence: ${active?.phrase||''}`:'';whole.hidden=!whole.textContent;
  dialog.querySelector('#pronunciationMeaning').textContent=active?.meaning||'';
  dialog.querySelector('.pronunciation-model').textContent=active?.compact?'🔊 Hear the word':practiceMode==='chunks'&&!isFinal?'🔊 Hear this chunk':'🔊 Hear full sentence';
 }
 function selectPracticeStep(index){if(attemptActive)return;resetAttempt();practiceMode='chunks';activeStep=Math.max(0,Math.min(index,practiceSteps.length));renderPractice();renderCaptureMode();setStatus(activeStep===practiceSteps.length?'Now connect every chunk into one natural sentence.':captureReadyStatus())}
 function setPracticeMode(mode){if(attemptActive||(mode==='chunks'&&practiceSteps.length<2))return;resetAttempt();practiceMode=mode;activeStep=mode==='chunks'?0:practiceSteps.length;renderPractice();renderCaptureMode();setStatus(captureReadyStatus())}
 function nextPracticeStep(){if(practiceMode!=='chunks')return;selectPracticeStep(Math.min(activeStep+1,practiceSteps.length))}
 function setStatus(message,kind=''){const node=dialog.querySelector('.pronunciation-status');node.textContent=message;node.className=`pronunciation-status ${kind}`.trim()}
 function draw(){
  if(!analyser)return;
  const canvas=dialog.querySelector('canvas'),ctx=canvas.getContext('2d'),data=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(data);ctx.fillStyle='#0f172a';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.lineWidth=3;ctx.strokeStyle='#5eead4';ctx.beginPath();let energy=0;data.forEach((value,index)=>{const x=index/(data.length-1)*canvas.width,y=value/128*canvas.height/2;energy+=(value-128)**2;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();
  if(recorder?.state==='recording'&&!stopStarted){const now=performance.now(),rms=Math.sqrt(energy/data.length)/128;if(rms>=VOICE_THRESHOLD){voiceFrames++;lastVoiceAt=now;if(!voiceStarted&&voiceFrames>=3){voiceStarted=true;setStatus('Voice detected — finish the phrase and I will stop automatically.','listening')}}else voiceFrames=0;if(voiceStarted&&now-lastVoiceAt>=SILENCE_STOP_MS){stop('silence');return}if(now-recordingStartedAt>=MAX_RECORDING_MS){stop('maximum-length');return}}
  waveFrame=requestAnimationFrame(draw)
 }
 function requestAutomaticStop(reason,delay=250){if(stopStarted||!attemptActive||autoStopTimer)return;autoStopTimer=setTimeout(()=>{autoStopTimer=0;if(attemptActive&&!stopStarted)stop(reason)},delay)}
 function recognitionResult(event){const resultList=Array.from(event.results),finalResult=resultList.some(result=>result.isFinal);transcript=resultList.map(result=>result[0]?.transcript||'').filter(Boolean).join(' ').trim();if(transcript)setStatus(`Japanese detected: ${transcript}`,'listening');if(finalResult&&transcript)requestAutomaticStop('final-transcript')}
 function finishResultsWhenReady(){if(resultsShown||!recordingReady||!recognitionDone)return;clearTimeout(resultTimer);showResults()}
 function prepareAttempt(){chunks=[];transcript='';recognitionError='';recordingReady=captureMode==='recognition';recognitionDone=captureMode==='recording';resultsShown=false;stopStarted=false;attemptActive=true;voiceStarted=false;voiceFrames=0;lastVoiceAt=0;recordingStartedAt=performance.now();clearTimeout(resultTimer);clearTimeout(recognitionStopTimer);clearTimeout(autoStopTimer);autoStopTimer=0;dialog.querySelector('.pronunciation-results').hidden=true;dialog.querySelector('.pronunciation-record').disabled=false;dialog.querySelector('.pronunciation-record').textContent='■ Stop now';dialog.querySelector('.pronunciation-record').classList.add('recording')}
 function startRecognitionCheck(){
  if(!Recognition){setCaptureMode('recording');return}
  prepareAttempt();
  recognition=new Recognition();recognition.lang='ja-JP';recognition.interimResults=true;recognition.continuous=false;recognition.onresult=recognitionResult;recognition.onspeechstart=()=>setStatus('Japanese speech detected — finish the phrase naturally.','listening');recognition.onspeechend=()=>setStatus('Speech finished — checking the Japanese transcript…','review');recognition.onerror=event=>{recognitionError=event.error||'recognition-error'};recognition.onend=()=>{attemptActive=false;recognitionDone=true;recordingReady=true;clearTimeout(recognitionStopTimer);finishResultsWhenReady()};
  try{recognition.start();setStatus('Listening only for Japanese… the browser has exclusive microphone access.','listening');resultTimer=setTimeout(()=>{if(attemptActive)stop('maximum-length')},MAX_RECORDING_MS)}catch{attemptActive=false;resultsShown=true;recognitionDone=recordingReady=true;recognitionError='start-failed';dialog.querySelector('.pronunciation-record').classList.remove('recording');dialog.querySelector('.pronunciation-record').textContent='🎙️ Try again';setStatus('Speech recognition could not start. Use Record & compare instead.','review')}
 }
 async function startRecordingComparison(){
  prepareAttempt();
  try{
   if(!navigator.mediaDevices?.getUserMedia){const error=new Error('getUserMedia is not available in this browser');error.name='NotSupportedError';throw error}
   setStatus('Waiting for microphone permission…','listening');stream=await navigator.mediaDevices.getUserMedia({audio:true});
   if(!window.MediaRecorder){const error=new Error('MediaRecorder is not available in this browser');error.name='NotSupportedError';throw error}const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(type=>window.MediaRecorder.isTypeSupported?.(type));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=()=>{attemptActive=false;recordingReady=true;finishResultsWhenReady()};recorder.start(500);
   const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass){const error=new Error('AudioContext is not available in this browser');error.name='NotSupportedError';throw error}audioContext=new AudioContextClass();if(audioContext.state==='suspended')try{await audioContext.resume()}catch{}analyser=audioContext.createAnalyser();analyser.fftSize=256;audioContext.createMediaStreamSource(stream).connect(analyser);draw();setStatus('Recording locally… I will stop after you finish speaking.','listening')
  }catch{attemptActive=false;resultsShown=true;stopStarted=true;if(recorder?.state==='recording')try{recorder.stop()}catch{};stream?.getTracks().forEach(track=>track.stop());audioContext?.close?.();recorder=stream=audioContext=analyser=null;dialog.querySelector('.pronunciation-record').disabled=false;dialog.querySelector('.pronunciation-record').classList.remove('recording');dialog.querySelector('.pronunciation-record').textContent='🎙️ Try again';setStatus('Microphone recording is unavailable. You can still hear and shadow the model.','review')}
 }
 function start(){captureMode==='recognition'?startRecognitionCheck():startRecordingComparison()}
 function stop(reason='manual'){
  if(stopStarted)return;stopStarted=true;clearTimeout(autoStopTimer);autoStopTimer=0;
  const recordButton=dialog.querySelector('.pronunciation-record');recordButton.disabled=true;recordButton.textContent='Finishing…';recordButton.classList.remove('recording');setStatus(captureMode==='recognition'?'Speech finished — checking the Japanese transcript…':'Finishing your private recording…','review');clearTimeout(resultTimer);resultTimer=setTimeout(()=>{try{recognition?.stop()}catch{};attemptActive=false;recognitionDone=true;recordingReady=true;showResults()},4000);
  cancelAnimationFrame(waveFrame);analyser=null;audioContext?.close?.();
  clearTimeout(recognitionStopTimer);if(recognition&&!recognitionDone)recognitionStopTimer=setTimeout(()=>{try{recognition?.stop()}catch{recognitionDone=true;finishResultsWhenReady()}},RECOGNITION_GRACE_MS);
  if(recorder?.state==='recording'){try{recorder.requestData?.()}catch{};try{recorder.stop()}catch{recordingReady=true}}else recordingReady=true;
  finishResultsWhenReady();
 }
 function toggle(){attemptActive?stop('manual'):start()}
 function showResults(){
  if(resultsShown)return;resultsShown=true;
  clearTimeout(resultTimer);clearTimeout(recognitionStopTimer);clearTimeout(autoStopTimer);
  stream?.getTracks().forEach(track=>track.stop());
  attemptActive=false;const checking=captureMode==='recognition',results=dialog.querySelector('.pronunciation-results'),heard=normalise(transcript),practisingChunk=practiceMode==='chunks'&&activeStep<practiceSteps.length,keywords=practisingChunk?[{label:targetPhrase(),forms:practiceForms[activeStep]||[targetPhrase()]}]:keywordList(active),matches=keywords.map(keyword=>({...keyword,heard:keyword.forms.some(form=>heard.includes(normalise(form)))})),missing=matches.filter(item=>!item.heard);
  if(checking&&!missing.length&&transcript.trim())completedSteps.add(practisingChunk?activeStep:'full');try{active?.onRecognitionResult?.({transcript:transcript.trim(),matched:Boolean(checking&&transcript.trim()&&!missing.length),retryable:Boolean(checking&&!transcript.trim()),error:recognitionError||''})}catch{}renderPractice();renderCaptureMode();
  const transcriptBox=results.querySelector('.pronunciation-transcript'),keywordBox=results.querySelector('.pronunciation-keywords'),sensei=results.querySelector('.pronunciation-sensei-feedback'),guidance=results.querySelector('.pronunciation-guidance');let pose='analysing',feedbackTitle='Listen like Sensei',feedback='Play the model, then your recording. Compare the rhythm, pauses and long vowels one detail at a time.',tone='neutral';if(checking&&!transcript.trim()){pose='encouraging';feedbackTitle='Let’s try that once more';feedback=recognitionError==='no-speech'?'I could not hear a clear attempt. Move a little closer, listen to the model, and speak in one relaxed phrase.':'I did not receive clear Japanese this time. Listen once more, then speak steadily without rushing.';tone='retry'}else if(checking&&!missing.length){pose='celebrating';feedbackTitle=practisingChunk?'That chunk landed clearly!':'Excellent — the whole phrase was clear!';feedback=practisingChunk?'Your key sounds were recognised. Listen once for rhythm, then move to the next chunk.':'Every important part was recognised. Now repeat it once more with the model’s rhythm and vowel length.';tone='success'}else if(checking&&missing.length<matches.length){pose='encouraging';feedbackTitle='Good progress — refine one part';feedback=`I heard part of the phrase clearly. Slow down slightly and give extra space to ${missing.map(item=>item.label).join('、')}.`;tone='partial'}else if(checking){pose='analysing';feedbackTitle='Build the phrase more slowly';feedback=`Let’s isolate ${missing.map(item=>item.label).join('、')}. Hear the model, say that part alone, then reconnect the sentence.`;tone='retry'}sensei.className=`pronunciation-sensei-feedback ${tone}`;sensei.querySelector('img').src=`media/guides/sensei/sensei-${pose}.webp`;sensei.querySelector('img').alt=`Sensei ${pose} after your pronunciation attempt`;sensei.querySelector('strong').textContent=feedbackTitle;guidance.textContent=feedback;results.hidden=false;transcriptBox.querySelector('b').textContent=checking?'What the browser heard':'Private recording ready';transcriptBox.querySelector('p').textContent=checking?(transcript.trim()||(recognitionError==='no-speech'?'No speech was detected. Move closer to the microphone and try again.':'The browser returned no clear Japanese transcript. Try once more, or switch to Record & compare.')):'Play your recording below and compare its rhythm, vowels and pauses with the model.';keywordBox.hidden=!checking;keywordBox.innerHTML=checking?matches.map(item=>`<span class="pronunciation-keyword ${item.heard?'heard':''}">${item.heard?'✓ Heard':'Try again'} · ${item.label}</span>`).join(''):'';
  const audio=results.querySelector('audio');if(objectUrl)URL.revokeObjectURL(objectUrl);if(chunks.length){objectUrl=URL.createObjectURL(new Blob(chunks,{type:recorder?.mimeType||'audio/webm'}));audio.src=objectUrl;audio.hidden=false}else audio.hidden=true;
  const next=results.querySelector('.pronunciation-next');next.hidden=practiceMode!=='chunks'||activeStep===practiceSteps.length;next.textContent=activeStep===practiceSteps.length-1?'Put it all together →':'Next chunk →';
  const recordButton=dialog.querySelector('.pronunciation-record');recordButton.disabled=false;recordButton.textContent=checking?'🎙️ Check again':'🎙️ Record again';setStatus(checking?(transcript.trim()?`Review ready — the browser heard: ${transcript.trim()}`:'No Japanese transcript was returned. Try again or use private playback.'):'Recording ready — compare it with the model.','review');requestAnimationFrame(()=>results.scrollIntoView({behavior:'smooth',block:'nearest'}));
 }
 function cleanup(){resultsShown=true;stopStarted=true;attemptActive=false;clearTimeout(resultTimer);clearTimeout(recognitionStopTimer);clearTimeout(autoStopTimer);if(recorder?.state==='recording')recorder.stop();try{recognition?.abort()}catch{};stream?.getTracks().forEach(track=>track.stop());cancelAnimationFrame(waveFrame);analyser=null;audioContext?.close?.();if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl='';recorder=recognition=stream=audioContext=null}
 function close(){cleanup();dialog?.close()}
 function open(options){ensureDialog();cleanup();active={phrase:options.phrase||'',reading:options.reading||'',meaning:options.meaning||'',keywords:options.keywords||[],compact:Boolean(options.compact),onRecognitionResult:typeof options.onRecognitionResult==='function'?options.onRecognitionResult:null};const suppliedChunks=Array.isArray(options.chunks)?options.chunks.filter(Boolean):[],prepared=(suppliedChunks.length?suppliedChunks:chunkPhrase(active.phrase)).map(item=>typeof item==='string'?{text:item,forms:[item]}:{text:item.text||item.label||'',forms:[item.text||item.label,item.reading,...(item.forms||[])].filter(Boolean)}).filter(item=>item.text);practiceSteps=prepared.map(item=>item.text);practiceForms=prepared.map(item=>item.forms);practiceMode=practiceSteps.length>1?'chunks':'full';activeStep=practiceMode==='chunks'?0:practiceSteps.length;completedSteps=new Set();if(!Recognition)captureMode='recording';dialog.querySelector('.pronunciation-head h2').textContent=active.compact?'Word pronunciation':'Pronunciation Coach';dialog.querySelector('.pronunciation-head p').textContent=active.compact?'Hear the word, then say it once naturally.':'Build it gradually, then say it naturally.';dialog.querySelector('.pronunciation-results').hidden=true;dialog.querySelector('.pronunciation-record').disabled=false;dialog.querySelector('.pronunciation-record').classList.remove('recording');renderPractice();renderCaptureMode();setStatus(captureReadyStatus());if(!dialog.open)dialog.showModal()}
 function addLaunch(container,extract,label='🎙️ Practise pronunciation'){
  if(!container||container.querySelector(':scope > .pronunciation-launch'))return;const button=document.createElement('button');button.type='button';button.className='pronunciation-launch';button.textContent=label;button.onclick=()=>open(extract());container.append(button)
 }
 function mountLaunchers(){
  document.querySelectorAll('.sl-intro').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('.sl-main-sentence')?.textContent,reading:card.querySelector('.sl-reading')?.textContent,meaning:card.querySelector('.sl-meaning')?.textContent,chunks:[...(card.parentElement?.querySelectorAll('.sl-breakdown .sl-chunk')||[])].map(node=>({text:node.querySelector('strong')?.textContent.trim(),reading:node.querySelector('small')?.textContent.trim()})).filter(item=>item.text)})));
  document.querySelectorAll('.theatre-shadow-card').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('p[lang="ja"]')?.textContent,reading:card.querySelector('small')?.textContent,meaning:card.querySelector('strong')?.textContent}),'🎙️ Coach important phrases'));
  document.querySelectorAll('.conversation-correct').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('strong[lang="ja"]')?.textContent,reading:card.querySelector('small')?.textContent,meaning:card.querySelector('p')?.textContent})));
  document.querySelectorAll('.manga-reading-card').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('.manga-japanese')?.textContent,reading:card.querySelector('.manga-reading')?.textContent,meaning:'Dialogue from this manga panel'}),'🎙️ Say this panel'));
 }
 const launchObserver=new MutationObserver(mountLaunchers);launchObserver.observe(document.documentElement,{childList:true,subtree:true});
 window.KaishiPronunciation={open,available:Boolean(Recognition||navigator.mediaDevices?.getUserMedia),recognitionAvailable:Boolean(Recognition)};mountLaunchers();
})();
