'use strict';
(()=>{
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 let dialog,stream,recorder,recognition,audioContext,analyser,waveFrame,chunks=[],transcript='',active=null,objectUrl='';
 const normalise=value=>String(value||'').toLowerCase().normalize('NFKC').replace(/[\s。、！？!?.,・「」『』（）()\-ー]/g,'');
 const keywordList=options=>{
  const supplied=(options.keywords||[]).map(item=>typeof item==='string'?{label:item,forms:[item]}:{label:item.label||item.forms?.[0],forms:item.forms||[item.label]}).filter(item=>item.label);
  if(supplied.length)return supplied.slice(0,5);
  const cleaned=String(options.phrase||'').replace(/[、。！？!?]/g,'');
  const phrase=cleaned.split(/(?:から|まで|って|では|には|は|が|を|に|で|と|も|へ|の)/).map(item=>item.trim()).filter(item=>item.length>1);
  return (phrase.length?phrase:[cleaned]).slice(0,4).map(label=>({label,forms:[label]}));
 };
 function ensureDialog(){
  if(dialog)return dialog;
  dialog=document.createElement('dialog');dialog.className='pronunciation-coach-dialog';dialog.id='pronunciationCoachDialog';
  dialog.innerHTML=`<section class="pronunciation-coach"><header class="pronunciation-head"><img src="media/guides/sensei/sensei-analysing.webp" alt="Sensei analysing your practice"><div><span class="eyebrow">Optional speaking practice</span><h2>Pronunciation Coach</h2><p>Useful evidence, never a made-up percentage.</p></div><button class="pronunciation-close" aria-label="Close">×</button></header><section class="pronunciation-phrase"><strong id="pronunciationPhrase" lang="ja"></strong><small id="pronunciationReading"></small><span id="pronunciationMeaning"></span></section><canvas class="pronunciation-wave" width="560" height="76" aria-label="Live microphone waveform"></canvas><div class="pronunciation-status" aria-live="polite">Hear the model, then record one natural attempt.</div><div class="pronunciation-actions"><button class="pronunciation-model audio">🔊 Hear model</button><button class="pronunciation-record primary">🎙️ Start recording</button></div><section class="pronunciation-results" hidden><div class="pronunciation-transcript"><b>What the device heard</b><p></p></div><div class="pronunciation-keywords"></div><p class="pronunciation-guidance"></p><audio controls></audio></section><small class="pronunciation-privacy">Your recording stays on this device and is discarded when this coach closes. Speech recognition availability depends on your browser.</small></section>`;
  document.body.append(dialog);dialog.querySelector('.pronunciation-close').onclick=close;dialog.addEventListener('close',cleanup);dialog.querySelector('.pronunciation-model').onclick=()=>speakJapanese(active?.phrase||'');dialog.querySelector('.pronunciation-record').onclick=toggle;
  return dialog;
 }
 function setStatus(message,kind=''){const node=dialog.querySelector('.pronunciation-status');node.textContent=message;node.className=`pronunciation-status ${kind}`.trim()}
 function draw(){if(!analyser)return;const canvas=dialog.querySelector('canvas'),ctx=canvas.getContext('2d'),data=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(data);ctx.fillStyle='#0f172a';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.lineWidth=3;ctx.strokeStyle='#5eead4';ctx.beginPath();data.forEach((value,index)=>{const x=index/(data.length-1)*canvas.width,y=value/128*canvas.height/2;index?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();waveFrame=requestAnimationFrame(draw)}
 function recognitionResult(event){for(let i=event.resultIndex;i<event.results.length;i++)if(event.results[i].isFinal)transcript+=`${event.results[i][0].transcript} `}
 async function start(){
  try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];transcript='';const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(type=>window.MediaRecorder?.isTypeSupported?.(type));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=showResults;recorder.start();audioContext=new (window.AudioContext||window.webkitAudioContext)();analyser=audioContext.createAnalyser();analyser.fftSize=256;audioContext.createMediaStreamSource(stream).connect(analyser);draw();if(Recognition){recognition=new Recognition();recognition.lang='ja-JP';recognition.interimResults=false;recognition.continuous=true;recognition.onresult=recognitionResult;recognition.onerror=()=>{};try{recognition.start()}catch{}}dialog.querySelector('.pronunciation-record').textContent='■ Stop and review';dialog.querySelector('.pronunciation-record').classList.add('recording');setStatus('Listening… say the complete phrase once at a natural pace.','listening')}
  catch(error){stream?.getTracks().forEach(track=>track.stop());audioContext?.close?.();stream=audioContext=analyser=null;setStatus('Microphone access is unavailable. You can still hear and shadow the model.','review')}
 }
 function stop(){if(recorder?.state==='recording')recorder.stop();try{recognition?.stop()}catch{};stream?.getTracks().forEach(track=>track.stop());cancelAnimationFrame(waveFrame);analyser=null;audioContext?.close?.();dialog.querySelector('.pronunciation-record').textContent='🎙️ Try again';dialog.querySelector('.pronunciation-record').classList.remove('recording');setStatus('Review your recording and the important phrases below.','review')}
 function toggle(){recorder?.state==='recording'?stop():start()}
 function showResults(){
  const results=dialog.querySelector('.pronunciation-results'),heard=normalise(transcript),keywords=keywordList(active),matches=keywords.map(keyword=>({...keyword,heard:keyword.forms.some(form=>heard.includes(normalise(form)))})),missing=matches.filter(item=>!item.heard);
  results.hidden=false;results.querySelector('.pronunciation-transcript p').textContent=transcript.trim()||(Recognition?'No clear Japanese transcript was returned. Listen to your recording and try once more.':'Speech recognition is not supported here; use playback to compare rhythm and pauses.');results.querySelector('.pronunciation-keywords').innerHTML=matches.map(item=>`<span class="pronunciation-keyword ${item.heard?'heard':''}">${item.heard?'✓ Heard':'Try again'} · ${item.label}</span>`).join('');results.querySelector('.pronunciation-guidance').textContent=!Recognition?'Focus on matching the model’s rhythm, pauses and vowel length.':missing.length?`Try once more, giving extra space and clarity to: ${missing.map(item=>item.label).join('、')}.`:'All important phrases were detected. Now compare your rhythm and vowel length with the model.';
  const audio=results.querySelector('audio');if(objectUrl)URL.revokeObjectURL(objectUrl);if(chunks.length){objectUrl=URL.createObjectURL(new Blob(chunks,{type:recorder?.mimeType||'audio/webm'}));audio.src=objectUrl;audio.hidden=false}else audio.hidden=true;
 }
 function cleanup(){if(recorder?.state==='recording')recorder.stop();try{recognition?.abort()}catch{};stream?.getTracks().forEach(track=>track.stop());cancelAnimationFrame(waveFrame);analyser=null;audioContext?.close?.();if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl='';recorder=recognition=stream=audioContext=null}
 function close(){cleanup();dialog?.close()}
 function open(options){ensureDialog();cleanup();active={phrase:options.phrase||'',reading:options.reading||'',meaning:options.meaning||'',keywords:options.keywords||[]};dialog.querySelector('#pronunciationPhrase').textContent=active.phrase;dialog.querySelector('#pronunciationReading').textContent=active.reading;dialog.querySelector('#pronunciationMeaning').textContent=active.meaning;dialog.querySelector('.pronunciation-results').hidden=true;dialog.querySelector('.pronunciation-record').textContent='🎙️ Start recording';dialog.querySelector('.pronunciation-record').classList.remove('recording');setStatus(Recognition?'Hear the model, then record one natural attempt.':'This browser can record playback practice, but cannot return a Japanese transcript.');if(!dialog.open)dialog.showModal()}
 function addLaunch(container,extract,label='🎙️ Practise pronunciation'){
  if(!container||container.querySelector(':scope > .pronunciation-launch'))return;const button=document.createElement('button');button.type='button';button.className='pronunciation-launch';button.textContent=label;button.onclick=()=>open(extract());container.append(button)
 }
 function mountLaunchers(){
  document.querySelectorAll('.sl-intro').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('.sl-main-sentence')?.textContent,reading:card.querySelector('.sl-reading')?.textContent,meaning:card.querySelector('.sl-meaning')?.textContent})));
  document.querySelectorAll('.theatre-shadow-card').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('p[lang="ja"]')?.textContent,reading:card.querySelector('small')?.textContent,meaning:card.querySelector('strong')?.textContent}),'🎙️ Coach important phrases'));
  document.querySelectorAll('.conversation-correct').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('strong[lang="ja"]')?.textContent,reading:card.querySelector('small')?.textContent,meaning:card.querySelector('p')?.textContent})));
  document.querySelectorAll('.manga-reading-card').forEach(card=>addLaunch(card,()=>({phrase:card.querySelector('.manga-japanese')?.textContent,reading:card.querySelector('.manga-reading')?.textContent,meaning:'Dialogue from this manga panel'}),'🎙️ Say this panel'));
 }
 const launchObserver=new MutationObserver(mountLaunchers);launchObserver.observe(document.documentElement,{childList:true,subtree:true});
 window.KaishiPronunciation={open,available:Boolean(navigator.mediaDevices?.getUserMedia),recognitionAvailable:Boolean(Recognition)};mountLaunchers();
})();
