-- Kaishi Quest v9.0.9 social polish
alter table public.kaishi_friend_requests add column if not exists accepted_at timestamptz;
update public.kaishi_friend_requests set accepted_at=coalesce(accepted_at,responded_at,created_at) where status='accepted' and accepted_at is null;
create or replace function public.kaishi_friend_count(target_user uuid) returns integer language sql security definer set search_path=public as $$ select count(*)::integer from public.kaishi_friend_requests where status='accepted' and (sender_id=target_user or recipient_id=target_user); $$;
create or replace function public.send_kaishi_friend_request(target_login text) returns uuid language plpgsql security definer set search_path=public as $$ declare target_id uuid; request_id uuid; begin select user_id into target_id from public.leaderboard_entries where lower(github_login)=lower(trim(target_login)) limit 1; if target_id is null then raise exception 'No Kaishi Quest learner was found.'; end if; if target_id=auth.uid() then raise exception 'You cannot add yourself.'; end if; if public.kaishi_friend_count(auth.uid())>=25 then raise exception 'You have reached the 25-friend limit.'; end if; if public.kaishi_friend_count(target_id)>=25 then raise exception 'That learner has reached the 25-friend limit.'; end if; if (select count(*) from public.kaishi_friend_requests where sender_id=auth.uid() and status='pending')>=10 then raise exception 'You already have 10 pending outgoing requests.'; end if; insert into public.kaishi_friend_requests(sender_id,recipient_id,status,accepted_at) values(auth.uid(),target_id,'pending',null) on conflict(sender_id,recipient_id) do update set status='pending',created_at=now(),responded_at=null,accepted_at=null returning id into request_id; return request_id; end $$;
create or replace function public.respond_kaishi_friend_request(request_id uuid,accept_request boolean) returns void language plpgsql security definer set search_path=public as $$ declare sender uuid; begin select sender_id into sender from public.kaishi_friend_requests where id=request_id and recipient_id=auth.uid() and status='pending'; if sender is null then raise exception 'Friend request not found.'; end if; if accept_request and (public.kaishi_friend_count(auth.uid())>=25 or public.kaishi_friend_count(sender)>=25) then raise exception 'The 25-friend limit has been reached.'; end if; update public.kaishi_friend_requests set status=case when accept_request then 'accepted' else 'declined' end,responded_at=now(),accepted_at=case when accept_request then now() else null end where id=request_id and recipient_id=auth.uid() and status='pending'; end $$;
create or replace function public.create_kaishi_friend_invite() returns uuid language plpgsql security definer set search_path=public as $$ declare t uuid; begin if (select count(*) from public.kaishi_friend_invites where inviter_id=auth.uid() and redeemed_at is null and expires_at>now())>=5 then raise exception 'You already have 5 active invitation links.'; end if; insert into public.kaishi_friend_invites(inviter_id) values(auth.uid()) returning token into t; return t; end $$;
drop function if exists public.get_kaishi_friends();
create function public.get_kaishi_friends() returns table(relationship_status text,request_id uuid,user_id uuid,github_login text,display_name text,avatar_key text,streak integer,xp integer,last_active_at timestamptz,accepted_at timestamptz) language sql security definer set search_path=public as $$ with r as(select case when status='pending' and recipient_id=auth.uid() then 'pending_incoming' when status='pending' and sender_id=auth.uid() then 'pending_outgoing' else status end relationship_status,id request_id,case when sender_id=auth.uid() then recipient_id else sender_id end friend_id,accepted_at from public.kaishi_friend_requests where sender_id=auth.uid() or recipient_id=auth.uid()) select r.relationship_status,r.request_id,e.user_id,e.github_login,e.display_name,e.avatar_key,coalesce(e.streak,0)::integer,coalesce(e.xp,0)::integer,e.updated_at,r.accepted_at from r join public.leaderboard_entries e on e.user_id=r.friend_id where r.relationship_status in('accepted','pending_incoming','pending_outgoing'); $$; grant execute on function public.get_kaishi_friends() to authenticated;
create or replace function public.get_kaishi_admin_users() returns table(user_id uuid,github_login text,display_name text,avatar_key text,xp integer,mastered integer,streak integer,opted_in boolean,created_at timestamptz,updated_at timestamptz,friend_count integer) language plpgsql security definer set search_path=public as $$ begin if lower(coalesce(auth.jwt()->'user_metadata'->>'user_name',''))<>'terryjread-sudo' then raise exception 'Owner access required.'; end if; return query select e.user_id,e.github_login,e.display_name,e.avatar_key,coalesce(e.xp,0)::integer,coalesce(e.mastered,0)::integer,coalesce(e.streak,0)::integer,coalesce(e.opted_in,true),e.created_at,e.updated_at,public.kaishi_friend_count(e.user_id) from public.leaderboard_entries e order by e.created_at desc; end $$; grant execute on function public.get_kaishi_admin_users() to authenticated;
create or replace function public.get_kaishi_admin_notification_counts() returns jsonb language plpgsql security definer set search_path=public as $$ declare c integer:=0; begin if lower(coalesce(auth.jwt()->'user_metadata'->>'user_name',''))<>'terryjread-sudo' then raise exception 'Owner access required.'; end if; if to_regclass('public.learning_card_reports') is not null then execute 'select count(*) from public.learning_card_reports where coalesce(reviewed,false)=false' into c; elsif to_regclass('public.kaishi_learning_reports') is not null then execute 'select count(*) from public.kaishi_learning_reports where coalesce(reviewed,false)=false' into c; end if; return jsonb_build_object('unreviewed_reports',c); end $$; grant execute on function public.get_kaishi_admin_notification_counts() to authenticated;
