import type { CheckpointLevel } from './types';

const teach = (title: string, explanation: string, examples: CheckpointLevel['teaching']['examples']): CheckpointLevel['teaching'] => ({ title, explanation, examples });

export const CHECKPOINT_LEVELS: CheckpointLevel[] = [
  { id: 1, title: 'Kana arrivals', location: 'Tokyo Haneda · Arrival Hall A', skill: 'kana', rule: 'DENY if the hiragana name is different on the two documents.', guidance: 'Look at one character at a time. The first shift is generous and has full support.', aid: 'full', seconds: 360, travellers: 6, teaching: teach('Senior Officer Mori: compare every sound', 'Hiragana represents sound units. A document only matches when every sound is identical; a single extra あ creates a different name.', [{ japanese: 'あい = あい', romaji: 'ai = ai', english: 'Match — APPROVE.' }, { japanese: 'あい ≠ あいあ', romaji: 'ai ≠ aia', english: 'Different final sound — DENY.' }]) },
  { id: 2, title: 'Kana expansion', location: 'Osaka Kansai · International Gate', skill: 'kana', rule: 'DENY when even one hiragana character does not match.', guidance: 'The first rule remains active while the character pool grows.', aid: 'full', seconds: 350, travellers: 6, teaching: teach('Senior Officer Mori: near is not equal', 'Japanese names are precise sound sequences. Do not approve on shape alone: read from left to right and compare each mora.', [{ japanese: 'かさ = かさ', romaji: 'kasa = kasa', english: 'Same sequence — APPROVE.' }, { japanese: 'かさ ≠ かし', romaji: 'kasa ≠ kashi', english: 'さ and し differ — DENY.' }]) },
  { id: 3, title: 'Date desk', location: 'Sapporo New Chitose · North Terminal', skill: 'numbers', rule: 'DENY if the birth year is inconsistent.', guidance: 'Use the Japanese number reading and the dates; do not rely on a translated answer.', aid: 'romaji', seconds: 335, travellers: 6, teaching: teach('Senior Officer Mori: years are evidence', 'Read the digits and their Japanese number words as the same fact. You are checking whether the visa repeats the passport’s birth year exactly.', [{ japanese: '1998年', romaji: 'sen kyuu hyaku kyuu juu hachi nen', english: '1998.' }, { japanese: '2001年', romaji: 'ni sen ichi nen', english: '2001 — a different year.' }]) },
  { id: 4, title: 'Audio window', location: 'Fukuoka Airport · Bay Gate', skill: 'listening', rule: 'Ask the traveller their age. DENY if the spoken Japanese answer conflicts with the visa.', guidance: 'Replay the answer as often as you need. This shift tests what you hear, not an English age label.', aid: 'romaji', seconds: 325, travellers: 6, teaching: teach('Senior Officer Mori: listen for the number', 'なんさいですか asks “How old are you?” Listen for the number before さい. The answer must agree with the age written in Japanese on the visa.', [{ japanese: 'にじゅうにさいです', romaji: 'nijuu ni sai desu', english: 'I am 22 years old.' }, { japanese: 'にじゅうよんさいです', romaji: 'nijuu yon sai desu', english: 'I am 24 years old.' }]) },
  { id: 5, title: 'Purpose of travel', location: 'Naha Airport · Island Arrivals', skill: 'vocabulary', rule: 'DENY if the stated purpose does not match the entry form.', guidance: 'Use your linked vocabulary and the handbook; do not approve a reading where a Japanese word is required.', aid: 'romaji', seconds: 315, travellers: 6, teaching: teach('Senior Officer Mori: word and reading have different jobs', 'A Japanese word can be written in Japanese and pronounced with its reading. The entry field asks for the word itself, so do not treat a reading as a matching record.', [{ japanese: 'にほんご', romaji: 'nihongo', english: 'Japanese language.' }, { japanese: 'にほんご (reading)', romaji: 'nihongo', english: 'A reading is not a replacement field.' }]) },
  { id: 6, title: 'Reading precision', location: 'Nagoya Central · Transit Control', skill: 'reading', rule: 'DENY if the furigana reading does not match the name.', guidance: 'One mora can change a reading. Check each sound.', aid: 'romaji', seconds: 305, travellers: 6, teaching: teach('Senior Officer Mori: furigana is a pronunciation record', 'Furigana tells you exactly how a name is read. Small vowels and ょ/ゅ sounds matter: きょう and きゅう are not interchangeable.', [{ japanese: '京子 → きょうこ', romaji: 'Kyoko', english: 'Correct reading.' }, { japanese: '京子 → きゅうこ', romaji: 'Kyuuko', english: 'Different sound — DENY.' }]) },
  { id: 7, title: 'Plans and wishes', location: 'Kyoto Station · Visitor Lane', skill: 'grammar', rule: 'DENY if the purpose sentence uses the 〜たい form incorrectly.', guidance: 'Use the grammar briefing and rulebook before you stamp.', aid: 'romaji', seconds: 295, travellers: 6, teaching: teach('Senior Officer Mori: expressing “want to”', 'Attach たいです to the verb stem to express a personal wish. りょこうします means “I travel”; りょこうしたいです means “I want to travel.”', [{ japanese: 'りょこうしたいです', romaji: 'ryokou shitai desu', english: 'I want to travel.' }, { japanese: 'にほんごをべんきょうしたいです', romaji: 'nihongo o benkyou shitai desu', english: 'I want to study Japanese.' }]) },
  { id: 8, title: 'Natural answers', location: 'Sendai Airport · East Gate', skill: 'listening', rule: 'APPROVE valid natural answers, even when they are phrased differently.', guidance: 'Listen for meaning, rather than matching the visible string.', aid: 'minimal', seconds: 285, travellers: 6, teaching: teach('Senior Officer Mori: meaning can survive variation', 'A traveller may say the same age naturally in more than one way. Compare the fact they communicate, not only the exact written order.', [{ japanese: 'にじゅうにさいです', romaji: 'nijuu ni sai desu', english: '22 years old.' }, { japanese: 'わたしは にじゅうにさいです', romaji: 'watashi wa nijuu ni sai desu', english: 'I am 22 years old.' }]) },
  { id: 9, title: 'Cross-check shift', location: 'Tokyo Station · Shinkansen Concourse', skill: 'compound', rule: 'Apply every active rule before you stamp.', guidance: 'Slow down. A careful inspector uses the rulebook.', aid: 'minimal', seconds: 275, travellers: 6, teaching: teach('Senior Officer Mori: build a checking order', 'Start with identity, then date, then reading, then purpose and audio. A fixed order stops a familiar detail from hiding a later mismatch.', [{ japanese: 'なまえ → ねん → よみ', romaji: 'namae → nen → yomi', english: 'Name → year → reading.' }, { japanese: 'もくてき → こたえ', romaji: 'mokuteki → kotae', english: 'Purpose → spoken answer.' }]) },
  { id: 10, title: 'Judgement call', location: 'Yokohama Port · International Ferry', skill: 'compound', rule: 'Use the written rule and the evidence. Honest mistakes and false records are not the same.', guidance: 'This is difficult, but every decision remains grounded in the language evidence.', aid: 'minimal', seconds: 265, travellers: 6, teaching: teach('Senior Officer Mori: explain the evidence', 'The rulebook still decides the stamp. Your job is to identify the language fact that conflicts, then give a short, kind explanation in the review.', [{ japanese: 'よみが ちがいます', romaji: 'yomi ga chigaimasu', english: 'The reading is different.' }, { japanese: 'ねんが ちがいます', romaji: 'nen ga chigaimasu', english: 'The year is different.' }]) },
];

export function checkpointLevel(id: number): CheckpointLevel { return CHECKPOINT_LEVELS[Math.min(Math.max(id, 1), CHECKPOINT_LEVELS.length) - 1]!; }
