import { z } from 'zod';
import { checkpointLevel } from '../domains/kotoba-checkpoint/content';
import { advanceCheckpoint, checkpointPassed, createCheckpointRun, judgeCheckpoint } from '../domains/kotoba-checkpoint/run';
import type { CheckpointCase, CheckpointLearnerWord, CheckpointRun, Verdict } from '../domains/kotoba-checkpoint/types';
import { playCheckpointAudio, playCheckpointEffect, startCheckpointAmbience, stopCheckpointAmbience } from '../platform/kotoba-checkpoint-audio';
import { createVersionedRepository, sessionStorage } from '../platform/storage';

type Host = { show?: (id: string) => void; introducedVocabulary?: () => unknown; recordDeskMisses?: (ids: string[]) => void; completeShift?: (ids: string[]) => void; recordCheckpointResult?: (result: { level: number; passed: boolean; credits: number; practiceIds: string[] }) => void };
const repo = createVersionedRepository<CheckpointRun>({ storage: sessionStorage(), key: 'kaishi-kotoba-checkpoint', version: 2, schema: z.custom<CheckpointRun>(value => Boolean(value && typeof value === 'object')) });
let lastCorrect: boolean | null = null;
const root = (): HTMLElement | null => document.querySelector<HTMLElement>('#senseiDesk');
const host = (): Host => (window.KaishiActivityPolicy?.kotobaCheckpoint || {}) as Host;
const escape = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char] || char));
function words(): CheckpointLearnerWord[] { const values = host().introducedVocabulary?.(); return Array.isArray(values) ? values.map(value => { const word = value as Record<string, unknown>; return { id: String(word.id || ''), word: String(word.word || ''), reading: String(word.reading || ''), meaning: String(word.meaning || ''), wordAudio: typeof word.wordAudio === 'string' ? word.wordAudio : undefined }; }).filter(word => word.id && word.word && word.reading && word.meaning) : []; }
const load = (): CheckpointRun => repo.load() || createCheckpointRun(1, words());
const save = (run: CheckpointRun): void => repo.save(run);
function supported(value: { japanese: string; romaji: string; english: string }, run: CheckpointRun): string { const aid = checkpointLevel(run.level).aid; return `<b lang="ja">${escape(value.japanese)}</b>${aid !== 'minimal' ? `<small>${escape(value.romaji)}</small>` : ''}${aid === 'full' ? `<em>${escape(value.english)}</em>` : ''}`; }
function passportMarkup(item: CheckpointCase): string { const identity = item.identity; const names = item.traveller.split(' '); return `<article class="checkpoint-passport"><header><span>日本国旅券</span><b>JAPAN PASSPORT</b><i>◉</i></header><div class="checkpoint-passport-body"><img src="media/kotoba-checkpoint/traveller-${escape(item.portrait)}.png" alt="${escape(item.traveller)}"><dl><dt>Type / 種類</dt><dd>P</dd><dt>Nationality / 国籍</dt><dd>${escape(identity.nationality)}</dd><dt>Surname / 姓</dt><dd>${escape(names.at(-1) || item.traveller)}</dd><dt>Given names / 名</dt><dd>${escape(names.slice(0, -1).join(' '))}</dd><dt>Date of birth / 生年月日</dt><dd>${escape(identity.birthDate)}</dd><dt>Sex / 性別</dt><dd>${identity.sex}</dd><dt>Passport No.</dt><dd>${escape(identity.passportNumber)}</dd><dt>Expiry / 有効期限</dt><dd>${escape(identity.expires)}</dd></dl></div><footer>P&lt;JPN${escape((names.at(-1) || '').toUpperCase())}&lt;&lt;${escape((names[0] || '').toUpperCase())}</footer></article>`; }
function briefing(run: CheckpointRun): string { const level = checkpointLevel(run.level); const lesson = level.teaching; return `<section class="checkpoint-shell"><div class="checkpoint-terminal checkpoint-intro"><div class="checkpoint-terminal-brand"><span>日本 入国管理局</span><b>KOTOBA CHECKPOINT</b></div><article class="checkpoint-brief checkpoint-briefing"><span class="checkpoint-route">SHIFT ${level.id} · ${escape(level.location)}</span><h2 class="checkpoint-shift-title">${escape(level.title)}</h2><div class="checkpoint-senior"><img src="media/profiles/master-base.webp" alt="Senior Officer Mori"><div><span>SENIOR OFFICER MORI</span><h1>${escape(lesson.title)}</h1><p>${escape(lesson.explanation)}</p></div></div><div class="checkpoint-examples"><span>WORKED EXAMPLES</span>${lesson.examples.map(example => `<article><button type="button" class="checkpoint-hear-example" data-checkpoint-lesson-audio="${escape(example.japanese)}" aria-label="Hear ${escape(example.japanese)}"><b lang="ja">${escape(example.japanese)}</b><span aria-hidden="true">🔊 Hear Japanese</span></button><small>${escape(example.romaji)}</small><em>${escape(example.english)}</em></article>`).join('')}</div><div class="checkpoint-rule-card"><span>SHIFT RULE</span><strong>${escape(level.rule)}</strong></div><p>${escape(level.guidance)}</p><div class="checkpoint-brief-actions"><button class="checkpoint-primary" data-checkpoint-start>Start 6-traveller shift <span>→</span></button><button data-checkpoint-tutorial>Tutorial &amp; controls</button><button data-checkpoint-exit>Return to Journey</button></div><p class="checkpoint-intro-note">Use the handbook whenever you need it. Reading aids phase out as your route progresses.</p></article></div></section>`; }
function tutorial(): string { return `<section class="checkpoint-shell"><div class="checkpoint-terminal checkpoint-intro"><article class="checkpoint-brief checkpoint-tutorial"><span class="checkpoint-route">HOW TO INSPECT</span><h1>One rule. One stamp.</h1><ol><li>Read the senior officer’s briefing and the pinned rulebook.</li><li>Check the passport identity details, then the arrival form.</li><li>Use Hear answer or the handbook whenever you need it.</li><li>Stamp APPROVE or DENY. You can pause at any time.</li></ol><div class="checkpoint-example"><b>Example</b><span>Passport name: あい</span><span>Arrival form: あい</span><strong>They match — stamp APPROVE.</strong></div><button class="checkpoint-primary" data-checkpoint-tutorial-close>Back to shift briefing</button></article></div></section>`; }
function report(run: CheckpointRun): string { const passed = checkpointPassed(run); const reward = run.correct * 4 + (passed ? 8 : 0); return `<section class="checkpoint-shell"><div class="checkpoint-terminal checkpoint-intro"><article class="checkpoint-report"><span class="checkpoint-seal ${passed ? 'pass' : 'fail'}">${passed ? 'CLEAR' : 'REVIEW'}</span><span class="checkpoint-route">${escape(checkpointLevel(run.level).location)}</span><h1>${passed ? 'Shift cleared' : 'Inspection review'}</h1><p>${run.correct}/${run.cases.length} inspections correct. ${passed ? `You earned ${run.credits} transit credits in total.` : 'Practice from this attempt is saved. Restart for another calm run at the rule.'}</p><div class="checkpoint-reward-row"><span>◎ ${reward} credits earned</span><span>▣ ${run.cases.some(item => item.practiceIds.length) ? 'Learning record updated' : 'Kana practice recorded'}</span></div><div class="checkpoint-brief-actions"><button class="checkpoint-primary" data-checkpoint-next>${passed && run.level < 10 ? 'Open next shift →' : passed ? 'Replay checkpoint' : 'Restart this shift'}</button><button data-checkpoint-exit>Return to Journey</button></div></article></div></section>`; }
function inspection(run: CheckpointRun): string { const active = run.cases[run.index]!; const level = checkpointLevel(run.level); const feedback = run.phase === 'feedback' ? `<section class="checkpoint-feedback ${lastCorrect ? 'is-correct' : 'is-wrong'}"><b>${lastCorrect ? 'Correct call' : 'Rule missed'}</b><p>${escape(active.explanation)}</p><button class="checkpoint-primary" data-checkpoint-continue>Next traveller →</button></section>` : ''; const pause = run.paused ? `<div class="checkpoint-pause" role="dialog" aria-modal="true"><span>LANE PAUSED</span><h2>Take your time.</h2><p>Your documents and timer are safely held here.</p><button class="checkpoint-primary" data-checkpoint-pause>Resume inspection</button></div>` : ''; return `<section class="checkpoint-shell"><div class="checkpoint-terminal"><header class="checkpoint-hud"><div><span>SHIFT ${level.id}</span><b>${run.index + 1}/${run.cases.length} travellers</b></div><div><span class="checkpoint-credit">◎ ${run.credits}</span><b data-checkpoint-clock>${run.remaining}s</b><button data-checkpoint-pause>Pause</button><button data-checkpoint-exit>Leave</button></div></header><main class="checkpoint-board ${run.phase === 'feedback' ? 'is-feedback' : ''}"><aside class="checkpoint-rulebook"><span>RULEBOOK · ${escape(level.skill)}</span><strong>${escape(level.rule)}</strong><p>${escape(level.guidance)}</p><button data-checkpoint-handbook>Open handbook</button></aside><section class="checkpoint-lane"><div class="checkpoint-traveller"><img src="media/kotoba-checkpoint/traveller-${escape(active.portrait)}.png" alt="${escape(active.traveller)}"><div><span>TRAVELLER AT WINDOW</span><h1>${escape(active.traveller)}</h1><p>${escape(active.city)}</p>${active.question ? `<button data-checkpoint-audio>🔊 Hear answer</button>` : '<span class="checkpoint-quiet">Documents ready for review</span>'}</div></div><div class="checkpoint-document-stack">${passportMarkup(active)}<article class="checkpoint-document entry"><header><span>ARRIVAL FORM</span><b>${escape(active.entry.label)}</b></header>${supported(active.entry, run)}${active.question ? `<div class="checkpoint-question"><span>Ask: ${escape(active.question.japanese)}</span><button data-checkpoint-audio>🔊 Hear answer</button></div>` : ''}</article></div><div class="checkpoint-stamps"><button class="checkpoint-stamp deny" data-checkpoint-stamp="deny"><span>×</span> DENY</button><button class="checkpoint-stamp approve" data-checkpoint-stamp="approve"><span>✓</span> APPROVE</button></div></section>${feedback}<aside class="checkpoint-handbook" hidden><button data-checkpoint-handbook-close>×</button><span>POCKET HANDBOOK</span><h2>Help is allowed.</h2><p>${escape(level.teaching.explanation)}</p><dl>${level.teaching.examples.map(example => `<dt>${escape(example.japanese)}</dt><dd>${escape(example.romaji)} · ${escape(example.english)}</dd>`).join('')}</dl></aside>${pause}</main></div></section>`; }
function render(): void { const target = root(); if (!target) return; const run = load(); target.innerHTML = run.phase === 'briefing' ? briefing(run) : run.phase === 'report' || run.phase === 'failed' ? report(run) : inspection(run); bind(); }
function start(): void { const run = load(); run.phase = 'inspect'; run.paused = false; save(run); startCheckpointAmbience(); render(); }
function decide(verdict: Verdict): void { const run = load(); const active = run.cases[run.index]!; const result = judgeCheckpoint(run, verdict); lastCorrect = active.expected === verdict; if (!lastCorrect) host().recordDeskMisses?.(active.practiceIds); save(result); playCheckpointEffect('stamp'); render(); }
function advance(): void { const before = load(); const run = advanceCheckpoint(before); save(run); if (run.phase === 'report' || run.phase === 'failed') { const practiceIds = run.cases.flatMap(item => item.practiceIds); host().recordCheckpointResult?.({ level: run.level, passed: run.phase === 'report', credits: run.credits - before.credits, practiceIds }); if (run.phase === 'report') host().completeShift?.(practiceIds); } render(); }
function next(): void { const run = load(); const level = run.phase === 'report' && run.level < 10 ? run.level + 1 : run.level; save(createCheckpointRun(level, words(), run.credits, run.phase === 'report' ? [...run.completedLevels, run.level] : run.completedLevels)); lastCorrect = null; render(); }
function exit(): void { stopCheckpointAmbience(); host().show?.('journey'); }
function bind(): void { const target = root(); if (!target) return; target.querySelector('[data-checkpoint-start]')?.addEventListener('click', start); target.querySelector('[data-checkpoint-tutorial]')?.addEventListener('click', () => { target.innerHTML = tutorial(); bind(); }); target.querySelector('[data-checkpoint-tutorial-close]')?.addEventListener('click', render); target.querySelector('[data-checkpoint-stamp="approve"]')?.addEventListener('click', () => decide('approve')); target.querySelector('[data-checkpoint-stamp="deny"]')?.addEventListener('click', () => decide('deny')); target.querySelector('[data-checkpoint-continue]')?.addEventListener('click', advance); target.querySelector('[data-checkpoint-next]')?.addEventListener('click', next); target.querySelectorAll('[data-checkpoint-exit]').forEach(button => button.addEventListener('click', exit)); target.querySelectorAll('[data-checkpoint-pause]').forEach(button => button.addEventListener('click', () => { const run = load(); run.paused = !run.paused; save(run); render(); })); target.querySelectorAll('[data-checkpoint-audio]').forEach(button => button.addEventListener('click', () => { const active = load().cases[load().index]; if (active) playCheckpointAudio(active.question?.answer || active.entry.romaji); })); target.querySelectorAll<HTMLElement>('[data-checkpoint-lesson-audio]').forEach(button => button.addEventListener('click', () => playCheckpointAudio(button.dataset.checkpointLessonAudio || ''))); target.querySelector('[data-checkpoint-handbook]')?.addEventListener('click', () => { const book = target.querySelector<HTMLElement>('.checkpoint-handbook'); if (book) book.hidden = false; }); target.querySelector('[data-checkpoint-handbook-close]')?.addEventListener('click', () => { const book = target.querySelector<HTMLElement>('.checkpoint-handbook'); if (book) book.hidden = true; }); }
function tick(): void { const run = load(); if (run.phase !== 'inspect' || run.paused) return; if (run.remaining <= 0) { run.phase = 'failed'; save(run); render(); return; } run.remaining -= 1; save(run); const clock = root()?.querySelector<HTMLElement>('[data-checkpoint-clock]'); if (clock) clock.textContent = `${run.remaining}s`; }
export function installKotobaCheckpoint(): void { window.setInterval(tick, 1000); document.querySelector<HTMLElement>('[data-experimental-nav="sensei-desk"]')?.addEventListener('click', render); window.addEventListener('kaishi-sensei-desk-host-ready', render); if (root()?.classList.contains('active')) render(); }
