import { z } from 'zod';
import { createVersionedRepository, sessionStorage } from '../platform/storage';
import { playSenseiDeskEffect, playSenseiDeskWordAudio, startSenseiDeskMusic, stopSenseiDeskMusic } from '../platform/sensei-desk-audio';

type Host = { show?: (id: string) => void; introducedVocabulary?: () => unknown; speak?: (text: string) => void; recordDeskMisses?: (ids: string[]) => void; completeShift?: (ids: string[]) => void; };
type Word = { id: string; word: string; reading: string; meaning: string; wordAudio?: string };
type Case = { id: string; traveller: string; city: string; passport: string; form: string; meaning: string; correct: boolean; rule: string; word?: Word };
type State = { version: 1; level: number; index: number; cases: Case[]; correct: number; mistakes: string[]; paused: boolean; startedAt: number; remaining: number; phase: 'briefing' | 'inspect' | 'feedback' | 'report' | 'failed'; };
const KEY = 'kaishi-kotoba-checkpoint';
const repo = createVersionedRepository<State>({ storage: sessionStorage(), key: KEY, version: 1, schema: z.custom<State>(value => Boolean(value && typeof value === 'object')) });
const KANA = ['あ','い','う','え','お','か','き','く','け','こ','さ','し','す','せ','そ'];
const NAMES = ['Aiko','Ren','Mio','Haru','Sora'];
const CITIES = ['Tokyo · Haneda','Osaka · Kansai','Sapporo · New Chitose','Fukuoka · Hakata','Naha · Okinawa'];
let lastVerdict: boolean | undefined;
function host(): Host { return (window.KaishiActivityPolicy?.senseiDesk || {}) as Host; }
function root(): HTMLElement | null { return document.querySelector<HTMLElement>('#senseiDesk'); }
function esc(v: unknown): string { return String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c] || c)); }
function words(): Word[] { const raw = host().introducedVocabulary?.(); return Array.isArray(raw) ? raw.map(item => { const x=item as Record<string,unknown>; return { id:String(x.id||''),word:String(x.word||''),reading:String(x.reading||''),meaning:String(x.meaning||''),wordAudio:typeof x.wordAudio==='string'?x.wordAudio:undefined }; }).filter(x=>x.id&&x.word&&x.reading&&x.meaning) : []; }
function makeCases(level: number): Case[] { const known = words(); return Array.from({length:Math.min(5,3+Math.floor((level-1)/3))},(_,i)=>{ const kana=KANA[(level*3+i)%KANA.length]!, word=known[i%Math.max(1,known.length)]; const mismatch=(i+level)%3===1; const useWord=Boolean(level>=5&&word); const passport=useWord?word!.word:kana; const form=useWord?(mismatch?word!.meaning:(level>=7?word!.reading:word!.word)):(mismatch?KANA[(KANA.indexOf(kana)+1)%KANA.length]!:kana); return { id:`${level}-${i}`,traveller:NAMES[i%NAMES.length]!,city:CITIES[(level+i)%CITIES.length]!,passport,form,meaning:useWord?word!.meaning:`Hiragana ${kana}`,correct:!mismatch,rule:useWord?'Entry form must match the taught Japanese word.':'Reject when the hiragana name differs between documents.',word:useWord?word:undefined }; }); }
function fresh(level=1): State { return {version:1,level,index:0,cases:makeCases(level),correct:0,mistakes:[],paused:false,startedAt:Date.now(),remaining:level<4?150:120,phase:'briefing'}; }
function state(): State { return repo.load() || fresh(); }
function save(s:State): void { repo.save(s); }
function current(s:State): Case { return s.cases[s.index]!; }
function render(): void { const s=state(), el=root(); if(!el)return; if(s.phase==='briefing'){ el.innerHTML=`<section class="checkpoint-shell"><div class="checkpoint-terminal"><header><span class="eyebrow">TOKYO TRANSIT AUTHORITY · LEVEL ${s.level}</span><h1>Kotoba Checkpoint</h1><p>Rulebook training. Every decision teaches Japanese.</p></header><article class="checkpoint-brief"><b>NEW RULE</b><h2>${esc(s.cases[0]?.rule)}</h2><p>Compare the traveller’s documents, use audio when it appears, then stamp APPROVE or DENY. You can pause at any time.</p><button class="primary" data-checkpoint-start>Open lane <span>→</span></button></article></div></section>`; bind(); return; }
 if(s.phase==='report'||s.phase==='failed'){ const passed=s.phase==='report'&&s.correct>=Math.ceil(s.cases.length*.6); el.innerHTML=`<section class="checkpoint-shell"><div class="checkpoint-terminal"><article class="checkpoint-report"><span class="checkpoint-seal ${passed?'pass':'fail'}">${passed?'CLEAR':'RETRY'}</span><h1>${passed?'Shift cleared':'Lane review required'}</h1><p>${s.correct}/${s.cases.length} inspections correct. ${passed?'Your next route is ready.':'The rulebook stays open—restart this shift when ready.'}</p><button class="primary" data-checkpoint-next>${passed?'Next checkpoint':'Restart shift'}</button><button data-checkpoint-exit>Return to Journey</button></article></div></section>`; bind(); return; }
 const c=current(s); el.innerHTML=`<section class="checkpoint-shell"><div class="checkpoint-terminal"><header class="checkpoint-hud"><span>LEVEL ${s.level} · TRAVELLER ${s.index+1}/${s.cases.length}</span><b data-checkpoint-clock>${s.paused?'PAUSED':`${s.remaining}s`}</b><button data-checkpoint-pause>${s.paused?'Resume':'Pause'}</button><button data-checkpoint-exit>Leave</button></header><main class="checkpoint-lane ${s.phase==='feedback'?'is-feedback':''}"><aside class="checkpoint-rulebook"><span>RULEBOOK</span><strong>${esc(c.rule)}</strong><small>Romaji and English support reduce as routes advance.</small></aside><section class="checkpoint-window"><div class="checkpoint-traveller"><i></i><h2>${esc(c.traveller)}</h2><p>${esc(c.city)}</p><button data-checkpoint-audio ${c.word?'':'disabled'}>🔊 Ask traveller</button></div><div class="checkpoint-documents"><article><span>PASSPORT</span><b lang="ja">${esc(c.passport)}</b><small>${esc(c.meaning)}</small></article><article><span>ENTRY FORM</span><b lang="ja">${esc(c.form)}</b><small>${s.level<4?esc(c.form):'Compare with the rulebook'}</small></article></div></section><footer class="checkpoint-stamps"><button class="checkpoint-stamp deny" data-checkpoint-stamp="deny">DENY</button><button class="checkpoint-stamp approve" data-checkpoint-stamp="approve">APPROVE</button></footer>${s.phase==='feedback'?`<div class="checkpoint-feedback ${lastVerdict?'good':'bad'}"><b>${lastVerdict?'Correct inspection':'Rule missed'}</b><span>${esc(c.rule)}</span><button data-checkpoint-continue>Continue</button></div>`:''}</main></div></section>`; bind(); }
function decide(approve:boolean):void { const s=state(), c=current(s), right=approve===c.correct; lastVerdict=right; if(right)s.correct++;else{s.mistakes.push(c.id);if(c.word)host().recordDeskMisses?.([c.word.id]);} s.phase='feedback'; save(s); playSenseiDeskEffect('stamp'); render(); }
function advance():void { const s=state(); if(s.index+1>=s.cases.length){ s.phase=s.correct>=Math.ceil(s.cases.length*.6)?'report':'failed'; if(s.phase==='report')host().completeShift?.(s.cases.flatMap(c=>c.word?[c.word.id]:[])); } else {s.index++;s.phase='inspect';} save(s); render(); }
function bind():void { const el=root(); if(!el)return; el.querySelector('[data-checkpoint-start]')?.addEventListener('click',()=>{const s=state();s.phase='inspect';save(s);startSenseiDeskMusic('calm');render();}); el.querySelector('[data-checkpoint-stamp="approve"]')?.addEventListener('click',()=>decide(true));el.querySelector('[data-checkpoint-stamp="deny"]')?.addEventListener('click',()=>decide(false));el.querySelector('[data-checkpoint-continue]')?.addEventListener('click',advance);el.querySelector('[data-checkpoint-next]')?.addEventListener('click',()=>{const s=state();save(fresh(s.phase==='report'?s.level+1:s.level));render();});el.querySelector('[data-checkpoint-pause]')?.addEventListener('click',()=>{const s=state();s.paused=!s.paused;save(s);render();});el.querySelector('[data-checkpoint-audio]')?.addEventListener('click',()=>{const c=current(state()); if(c.word)playSenseiDeskWordAudio(c.word.wordAudio,c.word.reading); else host().speak?.(c.passport);});el.querySelectorAll('[data-checkpoint-exit]').forEach(x=>x.addEventListener('click',()=>{stopSenseiDeskMusic();host().show?.('journey');})); }
function tick():void { const s=state();if(s.phase!=='inspect'||s.paused)return;if(s.remaining<=0){s.phase='failed';save(s);render();return;}s.remaining--;save(s);const clock=root()?.querySelector('[data-checkpoint-clock]');if(clock)clock.textContent=`${s.remaining}s`; }
export function installKotobaCheckpoint(): void { window.setInterval(tick,1000); const nav=document.querySelector<HTMLElement>('[data-experimental-nav="sensei-desk"]');nav?.addEventListener('click',render);window.addEventListener('kaishi-sensei-desk-host-ready',render); }
