export const CONTENT_DATA_FILES = [
  './data/japan-ready-v90.json',
  './data/sentence-lab.json',
  './data/lesson-story-scenes.json',
  './data/vocabulary.json',
  './data/katakana-core-10k.json',
  './data/vocabulary-orthography.json',
  './data/kana.json',
  './data/manga-stories.json',
  './data/conversations.json',
  './data/theatre-scenes.json',
  './data/grammar-path.json',
  './data/kanji-components.json',
  './memory-scenes.json',
  './data/anki-content-v72.json',
  './data/topics-v72.json',
  './data/learning-graph-v82.json',
  './visual-mnemonics.json',
] as const;

export const OFFLINE_CORE_FILES = [
  './', './index.html', './image-diagnostics.html', './manifest.webmanifest', './styles.css', './sentence-lab.css',
  './engagement-layer.css', './pronunciation-coach.css', './bonsai-progress.css', './vms.css',
  './version.js', './content-manifest.generated.js', './app.js', './journey.js',
  './roadmap-engine.js', './road-ahead.js', './journey-activities.js', './vms.js', './cloud.js',
  './reporting.js', './japan-ready.js', './supabase-config.js', './release-manager.js',
  './battle-listen.js', './dashboard-clarity.js', './touch-enhancements.js',
  './learning-ui.js', './carousel-navigation.js', './micro-practice.js', './sentence-lab.js',
  './adaptive-learning.js', './adaptive-reinforcement.js', './campfire-recall.js', './word-rain.js',
  './battle-ui-patch.js',
  ...CONTENT_DATA_FILES,
  './icons/icon-192.png', './icons/icon-512.png',
  './media/bonsai/bonsai-growth-stages.png', './media/bonsai/bonsai-condition-overlays.png',
  './media/guides/teacher-guide.webp', './media/guides/sensei/sensei-welcoming.webp',
  './media/guides/sensei/sensei-explaining.webp', './media/guides/sensei/sensei-celebrating.webp',
  './media/guides/sensei/sensei-encouraging.webp', './media/guides/sensei/sensei-pointing.webp',
  './media/guides/sensei/sensei-analysing.webp', './media/guides/aiko-guide-icon.webp',
  './media/celebrations/maneki-neko.li',
  './media/guides/aiko-guide-portrait.webp', './media/guides/aiko-guide-large.webp',
  './media/sentence-lab/sentence-lab-hero.webp',
  './media/journey-scenes/bamboo-scroll-tile.png',
  './media/experimental/kaishi-journey-hero.png',
  './media/experimental/heroes/summer.jpg', './media/experimental/heroes/autumn.jpg',
  './media/experimental/heroes/winter.jpg', './media/experimental/heroes/halloween.jpg',
  './media/experimental/heroes/christmas.jpg', './media/experimental/heroes/new-year.jpg',
  './media/experimental/heroes/tanabata.jpg',
  './media/battle-listen/arena-backdrop.jpg', './media/battle-listen/bgm.mp3',
  './media/battle-listen/kappa.png', './media/battle-listen/karakasa.png',
  './media/battle-listen/kitsune.png', './media/battle-listen/tanuki.png',
  './media/battle-listen/party-warrior.png', './media/battle-listen/party-mage.png',
  './media/battle-listen/party-guardian.png',
  './media/mnemonics/katakana-core-01-percent.png',
  ...Array.from({ length: 99 }, (_, index) => `./media/mnemonics/katakana-core-${String(index + 2).padStart(3, '0')}.png`),
  './media/profiles/guest-learner.webp', './media/profiles/boy-base.webp',
  './media/profiles/girl-base.webp', './media/profiles/master-base.webp',
  './media/profiles/man-base.webp', './media/profiles/woman-base.webp',
  './media/profiles/journey-girl-base.png', './media/profiles/journey-boy-base.png',
  './media/profiles/journey-friend-base.png', './media/profiles/journey-guide-base.png',
  './media/profiles/journey-girl-avatar.png', './media/profiles/journey-boy-avatar.png',
  './media/profiles/journey-friend-avatar.png',
] as const;
